import { Card } from './types'

const test: Card[] = [
    { id: 1, it: "one", pl: "jeden", presentIndicative: { singular: { first: "1-s1", second: "1-s2", third: "1-s3" }, plural: { first: "1-p1", second: "1-p2", third: "1-p3" }}},
    { id: 2, it: "two", pl: "dwa", presentIndicative: { singular: { first: "2-s1", second: "2-s2", third: "2-s3" }, plural: { first: "2-p1", second: "2-p2", third: "2-p3" }}},
    { id: 3, it: "three", pl: "trzy", presentIndicative: { singular: { first: "3-s1", second: "3-s2", third: "3-s3" }, plural: { first: "3-p1", second: "3-p2", third: "3-p3" }}},
    { id: 4, it: "four", pl: "cztery", presentIndicative: { singular: { first: "4-s1", second: "4-s2", third: "4-s3" }, plural: { first: "4-p1", second: "4-p2", third: "4-p3" }}},
    { id: 5, it: "five", pl: "pięć", presentIndicative: { singular: { first: "5-s1", second: "5-s2", third: "5-s3" }, plural: { first: "5-p1", second: "5-p2", third: "5-p3" }}},
    { id: 6, it: "six", pl: "sześć", presentIndicative: { singular: { first: "6-s1", second: "6-s2", third: "6-s3" }, plural: { first: "6-p1", second: "6-p2", third: "6-p3" }}},
]

const regular1A: Card[] = [
    { id: 1, it: "diventare", pl: "stawać się, zostawać", presentIndicative: { singular: { first: "divento", second: "diventi", third: "diventa" }, plural: { first: "diventiamo", second: "diventate", third:"diventano" }}},
    { id: 2, it: "abitare", pl: "mieszkać", presentIndicative: { singular: { first: "abito", second: "abiti", third: "abita" }, plural: { first: "abitiamo", second: "abitate", third:"abitano" }}},
    { id: 3, it: "imparare", pl: "uczyć się", presentIndicative: { singular: { first: "imparo", second: "impari", third: "impara" }, plural: { first: "impariamo", second: "imparate", third:"imparano" }}},
    { id: 4, it: "cucinare", pl: "gotować, przyrządzać", presentIndicative: { singular: { first: "cucino", second: "cucini", third: "cucina" }, plural: { first: "cuciniamo", second: "cucinate", third:"cucinano" }}},
    { id: 5, it: "lavorare", pl: "pracować", presentIndicative: { singular: { first: "lavoro", second: "lavori", third: "lavora" }, plural: { first: "lavoriamo", second: "lavorate", third:"lavorano" }}},
    { id: 6, it: "lavare; lavarsi", pl: "myć, prać; myć się", presentIndicative: { singular: { first: "lavo", second: "lavi", third: "lava" }, plural: { first: "laviamo", second: "lavate", third:"lavano" }}},
    { id: 7, it: "pranzare", pl: "jeść obiad", presentIndicative: { singular: { first: "pranzo", second: "pranzi", third: "pranza" }, plural: { first: "pranziamo", second: "pranzate", third:"pranzano" }}},
    { id: 8, it: "cenare", pl: "jeść kolację", presentIndicative: { singular: { first: "ceno", second: "ceni", third: "cena" }, plural: { first: "ceniamo", second: "cenate", third:"cenano" }}},
    { id: 9, it: "ascoltare", pl: "słuchać", presentIndicative: { singular: { first: "ascolto", second: "ascolti", third: "ascolta" }, plural: { first: "ascoltiamo", second: "ascoltate", third:"ascoltano" }}},
    { id: 10, it: "guardare", pl: "oglądać", presentIndicative: { singular: { first: "guardo", second: "guardi", third: "guarda" }, plural: { first: "guardiamo", second: "guardate", third:"guardano" }}},
    { id: 11, it: "trovare", pl: "znajdować", presentIndicative: { singular: { first: "trovo", second: "trovi", third: "trova" }, plural: { first: "troviamo", second: "trovate", third:"trovano" }}},
    { id: 12, it: "nuotare", pl: "pływać", presentIndicative: { singular: { first: "nuoto", second: "nuoti", third: "nuota" }, plural: { first: "nuotiamo", second: "nuotate", third:"nuotano" }}},
    { id: 13, it: "portare", pl: "nieść, nosić, przynosić, przyprowadzać", presentIndicative: { singular: { first: "porto", second: "porti", third: "porta" }, plural: { first: "portiamo", second: "portate", third:"portano" }}},
    { id: 14, it: "tornare", pl: "wracać", presentIndicative: { singular: { first: "torno", second: "torni", third: "torna" }, plural: { first: "torniamo", second: "tornate", third:"tornano" }}},
    { id: 15, it: "entrare", pl: "wchodzić", presentIndicative: { singular: { first: "entro", second: "entri", third: "entra" }, plural: { first: "entriamo", second: "entrate", third:"entrano" }}},
    { id: 16, it: "camminare", pl: "chodzić", presentIndicative: { singular: { first: "cammino", second: "cammini", third: "cammina" }, plural: { first: "camminiamo", second: "camminate", third:"camminano" }}},
    { id: 17, it: "tirare", pl: "ciągnąć", presentIndicative: { singular: { first: "tiro", second: "tiri", third: "tira" }, plural: { first: "tiriamo", second: "tirate", third:"tirano" }}},
    { id: 18, it: "ballare", pl: "tańczyć", presentIndicative: { singular: { first: "ballo", second: "balli", third: "balla" }, plural: { first: "balliamo", second: "ballate", third:"ballano" }}},
    { id: 19, it: "cantare", pl: "śpiewać", presentIndicative: { singular: { first: "canto", second: "canti", third: "canta" }, plural: { first: "cantiamo", second: "cantate", third:"cantano" }}},
    { id: 20, it: "usare", pl: "używać", presentIndicative: { singular: { first: "uso", second: "usi", third: "usa" }, plural: { first: "usiamo", second: "usate", third:"usano" }}},
    { id: 21, it: "iniziare", pl: "rozpoczynać, włączać", presentIndicative: { singular: { first: "inizio", second: "inizii", third: "inizia" }, plural: { first: "iniziiamo", second: "iniziate", third:"iniziano" }}},
    { id: 22, it: "parlare", pl: "mówić, rozmawiać", presentIndicative: { singular: { first: "parlo", second: "parli", third: "parla" }, plural: { first: "parliamo", second: "parlate", third:"parlano" }}},
    { id: 23, it: "ordinare", pl: "porządkować, rozkazywać, zamawiać", presentIndicative: { singular: { first: "ordino", second: "ordini", third: "ordina" }, plural: { first: "ordiniamo", second: "ordinate", third:"ordinano" }}},
    { id: 24, it: "pensare", pl: "myśleć", presentIndicative: { singular: { first: "penso", second: "pensi", third: "pensa" }, plural: { first: "pensiamo", second: "pensate", third:"pensano" }}},
    { id: 25, it: "telefonare", pl: "telefonować do kogoś", presentIndicative: { singular: { first: "telefono", second: "telefoni", third: "telefona" }, plural: { first: "telefoniamo", second: "telefonate", third:"telefonano" }}},
    { id: 26, it: "mandare", pl: "wysyłać", presentIndicative: { singular: { first: "mando", second: "mandi", third: "manda" }, plural: { first: "mandiamo", second: "mandate", third:"mandano" }}},
    { id: 27, it: "salutare", pl: "witać", presentIndicative: { singular: { first: "saluto", second: "saluti", third: "saluta" }, plural: { first: "salutiamo", second: "salutate", third:"salutano" }}},
    { id: 28, it: "incontrare; incontrarsi", pl: "spotykać; spotykać się", presentIndicative: { singular: { first: "incontro", second: "incontri", third: "incontra" }, plural: { first: "incontriamo", second: "incontrate", third:"incontrano" }}},
    { id: 29, it: "visitare", pl: "odwiedzać, zwiedzać", presentIndicative: { singular: { first: "visito", second: "visiti", third: "visita" }, plural: { first: "visitiamo", second: "visitate", third:"visitano" }}},
    { id: 30, it: "invitare", pl: "zapraszać", presentIndicative: { singular: { first: "invito", second: "inviti", third: "invita" }, plural: { first: "invitiamo", second: "invitate", third:"invitano" }}},
    { id: 31, it: "scusare", pl: "wybaczać", presentIndicative: { singular: { first: "scuso", second: "scusi", third: "scusa" }, plural: { first: "scusiamo", second: "scusate", third:"scusano" }}},
    { id: 32, it: "desiderare", pl: "życzyć sobie, chcieć", presentIndicative: { singular: { first: "desidero", second: "desideri", third: "desidera" }, plural: { first: "desideriamo", second: "desiderate", third:"desiderano" }}},
    { id: 33, it: "amare", pl: "kochać", presentIndicative: { singular: { first: "amo", second: "ami", third: "ama" }, plural: { first: "amiamo", second: "amate", third:"amano" }}},
    { id: 34, it: "sperare", pl: "mieć nadzieję", presentIndicative: { singular: { first: "spero", second: "speri", third: "spera" }, plural: { first: "speriamo", second: "sperate", third:"sperano" }}},
    { id: 35, it: "ricordare; ricordarsi", pl: "pamiętać kogoś/coś; przypominać sobie", presentIndicative: { singular: { first: "ricordo", second: "ricordi", third: "ricorda" }, plural: { first: "ricordiamo", second: "ricordate", third:"ricordano" }}},
    { id: 36, it: "aiutare", pl: "pomagać komuś", presentIndicative: { singular: { first: "aiuto", second: "aiuti", third: "aiuta" }, plural: { first: "aiutiamo", second: "aiutate", third:"aiutano" }}},
    { id: 37, it: "aspettare", pl: "czekać, oczekiwać na kogoś/coś", presentIndicative: { singular: { first: "aspetto", second: "aspetti", third: "aspetta" }, plural: { first: "aspettiamo", second: "aspettate", third:"aspettano" }}},
    { id: 38, it: "costare", pl: "kosztować", presentIndicative: { singular: { first: "costo", second: "costi", third: "costa" }, plural: { first: "costiamo", second: "costate", third:"costano" }}},
    { id: 39, it: "comprare", pl: "kupować", presentIndicative: { singular: { first: "compro", second: "compri", third: "compra" }, plural: { first: "compriamo", second: "comprate", third:"comprano" }}},
    { id: 40, it: "guadagnare", pl: "zarabiać", presentIndicative: { singular: { first: "guadagno", second: "guadagni", third: "guadagna" }, plural: { first: "guadagniamo", second: "guadagnate", third:"guadagnano" }}},
    { id: 41, it: "passare", pl: "mijać, spędzać (czas)", presentIndicative: { singular: { first: "passo", second: "passi", third: "passa" }, plural: { first: "passiamo", second: "passate", third:"passano" }}},
    { id: 42, it: "suonare", pl: "dzwonić, grać (na instrumencie)", presentIndicative: { singular: { first: "suono", second: "suoni", third: "suona" }, plural: { first: "suoniamo", second: "suonate", third:"suonano" }}},
    { id: 43, it: "bussare", pl: "pukać", presentIndicative: { singular: { first: "busso", second: "bussi", third: "bussa" }, plural: { first: "bussiamo", second: "bussate", third:"bussano" }}},
    { id: 44, it: "prestare", pl: "pożyczać", presentIndicative: { singular: { first: "presto", second: "presti", third: "presta" }, plural: { first: "prestiamo", second: "prestate", third:"prestano" }}},
    { id: 45, it: "formare", pl: "formować, tworzyć", presentIndicative: { singular: { first: "formo", second: "formi", third: "forma" }, plural: { first: "formiamo", second: "formate", third:"formano" }}},
    { id: 46, it: "pettinare; pettinarsi", pl: "czesać; czesać się", presentIndicative: { singular: { first: "pettino", second: "pettini", third: "pettina" }, plural: { first: "pettiniamo", second: "pettinate", third:"pettinano" }}},
    { id: 47, it: "bagnare", pl: "moczyć, zmoczyć", presentIndicative: { singular: { first: "bagno", second: "bagni", third: "bagna" }, plural: { first: "bagniamo", second: "bagnate", third:"bagnano" }}},
    { id: 48, it: "disegnare", pl: "rysować", presentIndicative: { singular: { first: "disegno", second: "disegni", third: "disegna" }, plural: { first: "disegniamo", second: "disegnate", third:"disegnano" }}},
    { id: 49, it: "mostrare", pl: "pokazywać", presentIndicative: { singular: { first: "mostro", second: "mostri", third: "mostra" }, plural: { first: "mostriamo", second: "mostrate", third:"mostrano" }}},
    { id: 50, it: "indirizzare", pl: "adresować", presentIndicative: { singular: { first: "indirizzo", second: "indirizzi", third: "indirizza" }, plural: { first: "indirizziamo", second: "indirizzate", third:"indirizzano" }}},
    { id: 51, it: "informare", pl: "informować", presentIndicative: { singular: { first: "informo", second: "informi", third: "informa" }, plural: { first: "informiamo", second: "informate", third:"informano" }}},
    { id: 52, it: "registrare", pl: "nagrywać", presentIndicative: { singular: { first: "registro", second: "registri", third: "registra" }, plural: { first: "registriamo", second: "registrate", third:"registrano" }}},
    { id: 53, it: "provare", pl: "przymierzać", presentIndicative: { singular: { first: "provo", second: "provi", third: "prova" }, plural: { first: "proviamo", second: "provate", third:"provano" }}},
    { id: 54, it: "presentare", pl: "przedstawiać, prezentować", presentIndicative: { singular: { first: "presento", second: "presenti", third: "presenta" }, plural: { first: "presentiamo", second: "presentate", third:"presentano" }}},
    { id: 55, it: "osservare", pl: "obserwować", presentIndicative: { singular: { first: "osservo", second: "osservi", third: "osserva" }, plural: { first: "osserviamo", second: "osservate", third:"osservano" }}},
    { id: 56, it: "insegnare", pl: "uczyć (kogoś)", presentIndicative: { singular: { first: "insegno", second: "insegni", third: "insegna" }, plural: { first: "insegniamo", second: "insegnate", third:"insegnano" }}},
    { id: 57, it: "domandare", pl: "pytać", presentIndicative: { singular: { first: "domando", second: "domandi", third: "domanda" }, plural: { first: "domandiamo", second: "domandate", third:"domandano" }}},
    { id: 58, it: "frequentare", pl: "chodzić; uczęszczać", presentIndicative: { singular: { first: "frequento", second: "frequenti", third: "frequenta" }, plural: { first: "frequentiamo", second: "frequentate", third:"frequentano" }}},
    { id: 59, it: "salare", pl: "solić", presentIndicative: { singular: { first: "salo", second: "sali", third: "sala" }, plural: { first: "saliamo", second: "salate", third:"salano" }}},
    { id: 60, it: "zuccherare", pl: "słodzić", presentIndicative: { singular: { first: "zucchero", second: "zuccheri", third: "zucchera" }, plural: { first: "zuccheriamo", second: "zuccherate", third:"zuccherano" }}},
    { id: 61, it: "confinare", pl: "graniczyć", presentIndicative: { singular: { first: "confino", second: "confini", third: "confina" }, plural: { first: "confiniamo", second: "confinate", third:"confinano" }}},
    { id: 62, it: "arrivare", pl: "przyjeżdżać, przybywać", presentIndicative: { singular: { first: "arrivo", second: "arrivi", third: "arriva" }, plural: { first: "arriviamo", second: "arrivate", third:"arrivano" }}},
    { id: 63, it: "ritornare", pl: "wracać (znowu?)", presentIndicative: { singular: { first: "ritorno", second: "ritorni", third: "ritorna" }, plural: { first: "ritorniamo", second: "ritornate", third:"ritornano" }}},
    { id: 64, it: "organizzare", pl: "organizować", presentIndicative: { singular: { first: "organizzo", second: "organizzi", third: "organizza" }, plural: { first: "organizziamo", second: "organizzate", third:"organizzano" }}},
    { id: 65, it: "bisognare", pl: "musieć (3 os. lp.), trzeba", presentIndicative: { singular: { first: "bisogno", second: "bisogni", third: "bisogna" }, plural: { first: "bisogniamo", second: "bisognate", third:"bisognano" }}},
    { id: 66, it: "rubare", pl: "kraść", presentIndicative: { singular: { first: "rubo", second: "rubi", third: "ruba" }, plural: { first: "rubiamo", second: "rubate", third:"rubano" }}},
    { id: 67, it: "regalare", pl: "podarować", presentIndicative: { singular: { first: "regalo", second: "regali", third: "regala" }, plural: { first: "regaliamo", second: "regalate", third:"regalano" }}},
    { id: 68, it: "sposare; sposarsi", pl: "poślubić (kogoś); brać ślub", presentIndicative: { singular: { first: "sposo", second: "sposi", third: "sposa" }, plural: { first: "sposiamo", second: "sposate", third:"sposano" }}},
    { id: 69, it: "restare", pl: "zostawać (o miejscu)", presentIndicative: { singular: { first: "resto", second: "resti", third: "resta" }, plural: { first: "restiamo", second: "restate", third:"restano" }}},
    { id: 70, it: "girare", pl: "skręcać", presentIndicative: { singular: { first: "giro", second: "giri", third: "gira" }, plural: { first: "giriamo", second: "girate", third:"girano" }}},
    { id: 71, it: "esercitare", pl: "ćwiczyć", presentIndicative: { singular: { first: "esercito", second: "eserciti", third: "esercita" }, plural: { first: "esercitiamo", second: "esercitate", third:"esercitano" }}},
    { id: 72, it: "raccontare", pl: "opowiadać", presentIndicative: { singular: { first: "racconto", second: "racconti", third: "racconta" }, plural: { first: "raccontiamo", second: "raccontate", third:"raccontano" }}},
    { id: 73, it: "guidare", pl: "kierować, prowadzić (auto)", presentIndicative: { singular: { first: "guido", second: "guidi", third: "guida" }, plural: { first: "guidiamo", second: "guidate", third:"guidano" }}},
    { id: 74, it: "ritardare", pl: "spóźniać się", presentIndicative: { singular: { first: "ritardo", second: "ritardi", third: "ritarda" }, plural: { first: "ritardiamo", second: "ritardate", third:"ritardano" }}},
    { id: 75, it: "detestare", pl: "nienawidzić, nie cierpieć", presentIndicative: { singular: { first: "detesto", second: "detesti", third: "detesta" }, plural: { first: "detestiamo", second: "detestate", third:"detestano" }}},
    { id: 76, it: "compilare", pl: "wypełniać (np. formularz)", presentIndicative: { singular: { first: "compilo", second: "compili", third: "compila" }, plural: { first: "compiliamo", second: "compilate", third:"compilano" }}},
    { id: 77, it: "sottolineare", pl: "podkreślać", presentIndicative: { singular: { first: "sottolineo", second: "sottolinei", third: "sottolinea" }, plural: { first: "sottolineiamo", second: "sottolineate", third:"sottolineano" }}},
    { id: 78, it: "segnare", pl: "zaznaczać", presentIndicative: { singular: { first: "segno", second: "segni", third: "segna" }, plural: { first: "segniamo", second: "segnate", third:"segnano" }}},
    { id: 79, it: "firmare", pl: "podpisywać", presentIndicative: { singular: { first: "firmo", second: "firmi", third: "firma" }, plural: { first: "firmiamo", second: "firmate", third:"firmano" }}},
    { id: 80, it: "timbrare", pl: "postawić pieczątkę", presentIndicative: { singular: { first: "timbro", second: "timbri", third: "timbra" }, plural: { first: "timbriamo", second: "timbrate", third:"timbrano" }}},
    { id: 81, it: "scappare", pl: "uciekać", presentIndicative: { singular: { first: "scappo", second: "scappi", third: "scappa" }, plural: { first: "scappiamo", second: "scappate", third:"scappano" }}},
    { id: 82, it: "fumare", pl: "palić (papierosy)", presentIndicative: { singular: { first: "fumo", second: "fumi", third: "fuma" }, plural: { first: "fumiamo", second: "fumate", third:"fumano" }}},
    { id: 83, it: "raffreddare; raffreddarsi", pl: "chłodzić; przeziębić się", presentIndicative: { singular: { first: "raffreddo", second: "raffreddi", third: "raffredda" }, plural: { first: "raffreddiamo", second: "raffreddate", third:"raffreddano" }}},
    { id: 84, it: "chiamare", pl: "wzywać, wołać", presentIndicative: { singular: { first: "chiamo", second: "chiami", third: "chiama" }, plural: { first: "chiamiamo", second: "chiamate", third:"chiamano" }}},
    { id: 85, it: "volare", pl: "latać, fruwać", presentIndicative: { singular: { first: "volo", second: "voli", third: "vola" }, plural: { first: "voliamo", second: "volate", third:"volano" }}},
    { id: 86, it: "preparare; prepararsi", pl: "przygotowywać; przygotowywać się", presentIndicative: { singular: { first: "preparo", second: "prepari", third: "prepara" }, plural: { first: "prepariamo", second: "preparate", third:"preparano" }}},
    { id: 87, it: "funzionare", pl: "działać, funkcjonować", presentIndicative: { singular: { first: "funziono", second: "funzioni", third: "funziona" }, plural: { first: "funzioniamo", second: "funzionate", third:"funzionano" }}},
]
const regular1B: Card[] = [
    { id: 88, it: "mangiare", pl: "jeść", presentIndicative: { singular: { first: "mangio", second: "mangi", third: "mangia" }, plural: { first: "mangiamo", second: "mangiate", third:"mangiano" }}},
    { id: 89, it: "studiare", pl: "uczyć się, studiować", presentIndicative: { singular: { first: "studio", second: "studi", third: "studia" }, plural: { first: "studiamo", second: "studiate", third:"studiano" }}},
    { id: 90, it: "lasciare", pl: "zostawiać, opuszczać", presentIndicative: { singular: { first: "lascio", second: "lasci", third: "lascia" }, plural: { first: "lasciamo", second: "lasciate", third:"lasciano" }}},
    { id: 91, it: "cambiare", pl: "zmieniać, wymieniać", presentIndicative: { singular: { first: "cambio", second: "cambi", third: "cambia" }, plural: { first: "cambiamo", second: "cambiate", third:"cambiano" }}},
    { id: 92, it: "cominciare", pl: "zaczynać (się)", presentIndicative: { singular: { first: "comincio", second: "cominci", third: "comincia" }, plural: { first: "cominciamo", second: "cominciate", third:"cominciano" }}},
    { id: 93, it: "risparmiare", pl: "oszczędzać", presentIndicative: { singular: { first: "risparmio", second: "risparmi", third: "risparmia" }, plural: { first: "risparmiamo", second: "risparmiate", third:"risparmiano" }}},
    { id: 94, it: "parcheggiare", pl: "parkować", presentIndicative: { singular: { first: "parcheggio", second: "parcheggi", third: "parcheggia" }, plural: { first: "parcheggiamo", second: "parcheggiate", third:"parcheggiano" }}},
    { id: 95, it: "spogliare; spogliarsi", pl: "rozbierać; rozbierać się", presentIndicative: { singular: { first: "spoglio", second: "spogli", third: "spoglia" }, plural: { first: "spogliamo", second: "spogliate", third:"spogliano" }}},
    { id: 96, it: "cambiare; cambiarsi", pl: "zamieniać, wymieniać; przebierać się", presentIndicative: { singular: { first: "cambio", second: "cambi", third: "cambia" }, plural: { first: "cambiamo", second: "cambiate", third:"cambiano" }}},
    { id: 97, it: "tagliare", pl: "kroić, ciąć", presentIndicative: { singular: { first: "taglio", second: "tagli", third: "taglia" }, plural: { first: "tagliamo", second: "tagliate", third:"tagliano" }}},
    { id: 98, it: "viaggiare", pl: "podróżować", presentIndicative: { singular: { first: "viaggio", second: "viaggi", third: "viaggia" }, plural: { first: "viaggiamo", second: "viaggiate", third:"viaggiano" }}},
    { id: 99, it: "sbagliare", pl: "mylić się", presentIndicative: { singular: { first: "sbaglio", second: "sbagli", third: "sbaglia" }, plural: { first: "sbagliamo", second: "sbagliate", third:"sbagliano" }}},
    { id: 100, it: "lanciare", pl: "rzucać", presentIndicative: { singular: { first: "lancio", second: "lanci", third: "lancia" }, plural: { first: "lanciamo", second: "lanciate", third:"lanciano" }}},
    { id: 101, it: "calciare", pl: "kopać (np. piłkę)", presentIndicative: { singular: { first: "calcio", second: "calci", third: "calcia" }, plural: { first: "calciamo", second: "calciate", third:"calciano" }}},
    { id: 102, it: "passeggiare", pl: "spacerować", presentIndicative: { singular: { first: "passegio", second: "passegi", third: "passegia" }, plural: { first: "passegiamo", second: "passegiate", third:"passegiano" }}},
]
const regular2: Card[] = [
    { id: 103, it: "prendere", pl: "brać, kupować, jeść, pić", presentIndicative: { singular: { first: "prendo", second: "prendi", third: "prende" }, plural: { first: "prendiamo", second: "prendete", third:"prendono" }}},
    { id: 104, it: "mettere", pl: "kłaść, zakładać, stawiać", presentIndicative: { singular: { first: "metto", second: "metti", third: "mette" }, plural: { first: "mettiamo", second: "mettete", third:"mettono" }}},
    { id: 105, it: "vedere; vedersi", pl: "widzieć; widzieć się", presentIndicative: { singular: { first: "vedo", second: "vedi", third: "vede" }, plural: { first: "vediamo", second: "vedete", third:"vedono" }}},
    { id: 106, it: "vendere", pl: "sprzedawać", presentIndicative: { singular: { first: "vendo", second: "vendi", third: "vende" }, plural: { first: "vendiamo", second: "vendete", third:"vendono" }}},
    { id: 107, it: "chiedere", pl: "pytać, prosić", presentIndicative: { singular: { first: "chiedo", second: "chiedi", third: "chiede" }, plural: { first: "chiediamo", second: "chiedete", third:"chiedono" }}},
    { id: 108, it: "rispondere", pl: "odpowiadać", presentIndicative: { singular: { first: "rispondo", second: "rispondi", third: "risponde" }, plural: { first: "rispondiamo", second: "rispondete", third:"rispondono" }}},
    { id: 109, it: "ripetere", pl: "powtarzać", presentIndicative: { singular: { first: "ripeto", second: "ripeti", third: "ripete" }, plural: { first: "ripetiamo", second: "ripetete", third:"ripetono" }}},
    { id: 110, it: "vivere", pl: "żyć, mieszkać", presentIndicative: { singular: { first: "vivo", second: "vivi", third: "vive" }, plural: { first: "viviamo", second: "vivete", third:"vivono" }}},
    { id: 111, it: "nascere", pl: "urodzić się", presentIndicative: { singular: { first: "nasco", second: "nasci", third: "nasce" }, plural: { first: "nasciamo", second: "nascete", third:"nascono" }}},
    { id: 112, it: "crescere", pl: "rosnąć", presentIndicative: { singular: { first: "cresco", second: "cresci", third: "cresce" }, plural: { first: "cresciamo", second: "crescete", third:"crescono" }}},
    { id: 113, it: "perdere; perdersi", pl: "przegrać, stracić; gubić się", presentIndicative: { singular: { first: "perdo", second: "perdi", third: "perde" }, plural: { first: "perdiamo", second: "perdete", third:"perdono" }}},
    { id: 114, it: "scendere", pl: "schodzić, wysiadać", presentIndicative: { singular: { first: "scendo", second: "scendi", third: "scende" }, plural: { first: "scendiamo", second: "scendete", third:"scendono" }}},
    { id: 115, it: "scrivere", pl: "pisać", presentIndicative: { singular: { first: "scrivo", second: "scrivi", third: "scrive" }, plural: { first: "scriviamo", second: "scrivete", third:"scrivono" }}},
    { id: 116, it: "rompere", pl: "łamać, rozbijać, tłuc", presentIndicative: { singular: { first: "rompo", second: "rompi", third: "rompe" }, plural: { first: "rompiamo", second: "rompete", third:"rompono" }}},
    { id: 117, it: "correre", pl: "biegać", presentIndicative: { singular: { first: "corro", second: "corri", third: "corre" }, plural: { first: "corriamo", second: "correte", third:"corrono" }}},
    { id: 118, it: "rendere", pl: "oddawać", presentIndicative: { singular: { first: "rendo", second: "rendi", third: "rende" }, plural: { first: "rendiamo", second: "rendete", third:"rendono" }}},
    { id: 119, it: "chiudere", pl: "zamykać", presentIndicative: { singular: { first: "chiudo", second: "chiudi", third: "chiude" }, plural: { first: "chiudiamo", second: "chiudete", third:"chiudono" }}},
    { id: 120, it: "spingere", pl: "pchać", presentIndicative: { singular: { first: "spingo", second: "spingi", third: "spinge" }, plural: { first: "spingiamo", second: "spingete", third:"spingono" }}},
    { id: 121, it: "accendere", pl: "włączać, zapalać", presentIndicative: { singular: { first: "accendo", second: "accendi", third: "accende" }, plural: { first: "accendiamo", second: "accendete", third:"accendono" }}},
    { id: 122, it: "credere", pl: "wierzyć, uważać", presentIndicative: { singular: { first: "credo", second: "credi", third: "crede" }, plural: { first: "crediamo", second: "credete", third:"credono" }}},
    { id: 123, it: "godere", pl: "cieszyć się czymś, korzystać z czegoś", presentIndicative: { singular: { first: "godo", second: "godi", third: "gode" }, plural: { first: "godiamo", second: "godete", third:"godono" }}},
    { id: 124, it: "leggere", pl: "czytać", presentIndicative: { singular: { first: "leggo", second: "leggi", third: "legge" }, plural: { first: "leggiamo", second: "leggete", third:"leggono" }}},
    { id: 125, it: "vincere", pl: "zwyciężać", presentIndicative: { singular: { first: "vinco", second: "vinci", third: "vince" }, plural: { first: "vinciamo", second: "vincete", third:"vincono" }}},
    { id: 126, it: "conoscere; conoscersi", pl: "znać; znać się", presentIndicative: { singular: { first: "conosco", second: "conosci", third: "conosce" }, plural: { first: "conosciamo", second: "conoscete", third:"conoscono" }}},
    { id: 127, it: "proteggere", pl: "chronić", presentIndicative: { singular: { first: "proteggo", second: "proteggi", third: "protegge" }, plural: { first: "proteggiamo", second: "proteggete", third:"proteggono" }}},
    { id: 128, it: "distruggere", pl: "niszczyć", presentIndicative: { singular: { first: "distruggo", second: "distruggi", third: "distrugge" }, plural: { first: "distruggiamo", second: "distruggete", third:"distruggono" }}},
    { id: 129, it: "spendere", pl: "wydawać (pieniądze)", presentIndicative: { singular: { first: "spendo", second: "spendi", third: "spende" }, plural: { first: "spendiamo", second: "spendete", third:"spendono" }}},
    { id: 130, it: "dipingere", pl: "malować", presentIndicative: { singular: { first: "dipingo", second: "dipingi", third: "dipinge" }, plural: { first: "dipingiamo", second: "dipingete", third:"dipingono" }}},
    { id: 131, it: "descrivere", pl: "opisywać", presentIndicative: { singular: { first: "descrivo", second: "descrivi", third: "descrive" }, plural: { first: "descriviamo", second: "descrivete", third:"descrivono" }}},
    { id: 132, it: "correggere", pl: "sprawdzać, poprawiać", presentIndicative: { singular: { first: "correggo", second: "correggi", third: "corregge" }, plural: { first: "correggiamo", second: "correggete", third:"correggono" }}},
    { id: 133, it: "piovere", pl: "padać (o deszczu)", presentIndicative: { singular: { first: "piovo", second: "piovi", third: "piove" }, plural: { first: "pioviamo", second: "piovete", third:"piovono" }}},
    { id: 134, it: "uccidere", pl: "zabijać", presentIndicative: { singular: { first: "uccido", second: "uccidi", third: "uccide" }, plural: { first: "uccidiamo", second: "uccidete", third:"uccidono" }}},
    { id: 135, it: "ricevere", pl: "dostawać, otrzymywać", presentIndicative: { singular: { first: "ricevo", second: "ricevi", third: "riceve" }, plural: { first: "riceviamo", second: "ricevete", third:"ricevono" }}},
    { id: 136, it: "cadere", pl: "upadać, spadać", presentIndicative: { singular: { first: "cado", second: "cadi", third: "cade" }, plural: { first: "cadiamo", second: "cadete", third:"cadono" }}},
    { id: 137, it: "ridere", pl: "śmiać się", presentIndicative: { singular: { first: "rido", second: "ridi", third: "ride" }, plural: { first: "ridiamo", second: "ridete", third:"ridono" }}},
    { id: 138, it: "sorridere", pl: "uśmiechać się", presentIndicative: { singular: { first: "sorrido", second: "sorridi", third: "sorride" }, plural: { first: "sorridiamo", second: "sorridete", third:"sorridono" }}},
    { id: 139, it: "sorprendere", pl: "zaskakiwać, dziwić", presentIndicative: { singular: { first: "sorprendo", second: "sorprendi", third: "sorprende" }, plural: { first: "sorprendiamo", second: "sorprendete", third:"sorprendono" }}},
    { id: 140, it: "permettere", pl: "pozwalać, zezwalać", presentIndicative: { singular: { first: "permetto", second: "permetti", third: "permette" }, plural: { first: "permettiamo", second: "permettete", third:"permettono" }}},
    { id: 141, it: "battere; battersi", pl: "bić, uderzać; bić się, walczyć", presentIndicative: { singular: { first: "batto", second: "batti", third: "batte" }, plural: { first: "battiamo", second: "battete", third:"battono" }}},
    { id: 142, it: "piangere", pl: "płakać", presentIndicative: { singular: { first: "piango", second: "piangi", third: "piange" }, plural: { first: "piangiamo", second: "piangete", third:"piangono" }}},
]
const regular3A: Card[] = [
    { id: 143, it: "sentire", pl: "słyszeć, czuć", presentIndicative: { singular: { first: "sento", second: "senti", third: "sente" }, plural: { first: "sentiamo", second: "sentite", third:"sentono" }}},
    { id: 144, it: "dormire", pl: "spać", presentIndicative: { singular: { first: "dormo", second: "dormi", third: "dorme" }, plural: { first: "dormiamo", second: "dormite", third:"dormono" }}},
    { id: 145, it: "partire", pl: "wyjeżdżać", presentIndicative: { singular: { first: "parto", second: "parti", third: "parte" }, plural: { first: "partiamo", second: "partite", third:"partono" }}},
    { id: 146, it: "coprire", pl: "przykrywać", presentIndicative: { singular: { first: "copro", second: "copri", third: "copre" }, plural: { first: "copriamo", second: "coprite", third:"coprono" }}},
    { id: 147, it: "scoprire", pl: "odkrywać", presentIndicative: { singular: { first: "scopro", second: "scopri", third: "scopre" }, plural: { first: "scopriamo", second: "scoprite", third:"scoprono" }}},
    { id: 148, it: "aprire", pl: "otwierać", presentIndicative: { singular: { first: "apro", second: "apri", third: "apre" }, plural: { first: "apriamo", second: "aprite", third:"aprono" }}},
    { id: 149, it: "offrire", pl: "ofiarować, oferować", presentIndicative: { singular: { first: "offro", second: "offri", third: "offre" }, plural: { first: "offriamo", second: "offrite", third:"offrono" }}},
    { id: 150, it: "soffrire", pl: "cierpieć", presentIndicative: { singular: { first: "soffro", second: "soffri", third: "soffre" }, plural: { first: "soffriamo", second: "soffrite", third:"soffrono" }}},
    { id: 151, it: "servire", pl: "służyć", presentIndicative: { singular: { first: "servo", second: "servi", third: "serve" }, plural: { first: "serviamo", second: "servite", third:"servono" }}},
]
const regular3B: Card[] = [
    { id: 152, it: "finire", pl: "kończyć", presentIndicative: { singular: { first: "finisco", second: "finisci", third: "finisce" }, plural: { first: "finiamo", second: "finite", third:"finiscono" }}},
    { id: 153, it: "capire", pl: "rozumieć", presentIndicative: { singular: { first: "capisco", second: "capisci", third: "capisce" }, plural: { first: "capiamo", second: "capite", third:"capiscono" }}},
    { id: 154, it: "dimagrire", pl: "chudnąć", presentIndicative: { singular: { first: "dimagrisco", second: "dimagrisci", third: "dimagrisce" }, plural: { first: "dimagriamo", second: "dimagrite", third:"dimagriscono" }}},
    { id: 155, it: "pulire", pl: "czyścić", presentIndicative: { singular: { first: "pulisco", second: "pulisci", third: "pulisce" }, plural: { first: "puliamo", second: "pulite", third:"puliscono" }}},
    { id: 156, it: "unire", pl: "jednoczyć, łączyć", presentIndicative: { singular: { first: "unisco", second: "unisci", third: "unisce" }, plural: { first: "uniamo", second: "unite", third:"uniscono" }}},
    { id: 157, it: "preferire", pl: "woleć", presentIndicative: { singular: { first: "preferisco", second: "preferisci", third: "preferisce" }, plural: { first: "preferiamo", second: "preferite", third:"preferiscono" }}},
    { id: 158, it: "costruire", pl: "budować, tworzyć", presentIndicative: { singular: { first: "costruisco", second: "costruisci", third: "costruisce" }, plural: { first: "costruiamo", second: "costruite", third:"costruiscono" }}},
    { id: 159, it: "restituire", pl: "zwracać, oddawać", presentIndicative: { singular: { first: "restituisco", second: "restituisci", third: "restituisce" }, plural: { first: "restituiamo", second: "restituite", third:"restituiscono" }}},
    { id: 160, it: "spedire", pl: "wysyłać (pocztą)", presentIndicative: { singular: { first: "spedisco", second: "spedisci", third: "spedisce" }, plural: { first: "spediamo", second: "spedite", third:"spediscono" }}},
]
const regular3AB: Card[] = [
    { id: 161, it: "tossire", pl: "kaszleć", presentIndicative: { singular: { first: "tosso / tossisco", second: "tossi / tossisci", third: "tosse / tossisce" }, plural: { first: "tossiamo / tossiamo", second: "tossite / tossite", third:"tossono / tossiscono" }}},
    { id: 162, it: "mentire", pl: "kłamać", presentIndicative: { singular: { first: "mento / mentisco", second: "menti / mentisci", third: "mente / mentisce" }, plural: { first: "mentiamo / mentiamo", second: "mentite / mentite", third:"mentono / mentiscono" }}},
]
const regularReflexive: Card[] = [
    { id: 163, it: "chiamarsi", pl: "nazywać się", presentIndicative: { singular: { first: "mi chiamo", second: "ti chiami", third: "si chiama" }, plural: { first: "ci chiamiamo", second: "vi chiamate", third:"si chiamano" }}},
    { id: 164, it: "comportarsi", pl: "zachowywać się", presentIndicative: { singular: { first: "mi comporto", second: "ti comporti", third: "si comporta" }, plural: { first: "ci comportiamo", second: "vi comportate", third:"si comportano" }}},
    { id: 165, it: "scusarsi", pl: "przeprosić, przepraszać", presentIndicative: { singular: { first: "mi scuso", second: "ti scusi", third: "si scusa" }, plural: { first: "ci scusiamo", second: "vi scusate", third:"si scusano" }}},
    { id: 166, it: "abituarsi", pl: "przyzwyczaić się", presentIndicative: { singular: { first: "mi abituo", second: "ti abitui", third: "si abitua" }, plural: { first: "ci abituiamo", second: "vi abituate", third:"si abituano" }}},
    { id: 167, it: "alzarsi", pl: "wstawać", presentIndicative: { singular: { first: "mi alzo", second: "ti alzi", third: "si alza" }, plural: { first: "ci alziamo", second: "vi alzate", third:"si alzano" }}},
    { id: 168, it: "ritrovarsi", pl: "odnaleźć się", presentIndicative: { singular: { first: "mi ritrovo", second: "ti ritrovi", third: "si ritrova" }, plural: { first: "ci ritroviamo", second: "vi ritrovate", third:"si ritrovano" }}},
    { id: 169, it: "concentrarsi", pl: "koncentrować się", presentIndicative: { singular: { first: "mi concentro", second: "ti concentri", third: "si concentra" }, plural: { first: "ci concentriamo", second: "vi concentrate", third:"si concentrano" }}},
    { id: 170, it: "addormentarsi", pl: "zasnąć", presentIndicative: { singular: { first: "mi addormento", second: "ti addormenti", third: "si addormenta" }, plural: { first: "ci addormentiamo", second: "vi addormentate", third:"si addormentano" }}},
    { id: 171, it: "ammalarsi", pl: "zachorować", presentIndicative: { singular: { first: "mi ammalo", second: "ti ammali", third: "si ammala" }, plural: { first: "ci ammaliamo", second: "vi ammalate", third:"si ammalano" }}},
    { id: 172, it: "esprimersi", pl: "wyrażać się", presentIndicative: { singular: { first: "mi esprimo", second: "ti esprimi", third: "si esprime" }, plural: { first: "ci esprimiamo", second: "vi esprimete", third:"si esprimono" }}},
    { id: 173, it: "vestirsi", pl: "ubierać się", presentIndicative: { singular: { first: "mi vesto", second: "ti vesti", third: "si veste" }, plural: { first: "ci vestiamo", second: "vi vestite", third:"si vestono" }}},
    { id: 174, it: "divertirsi", pl: "bawić się, spędzać miło czas", presentIndicative: { singular: { first: "mi diverto", second: "ti diverti", third: "si diverte" }, plural: { first: "ci divertiamo", second: "vi divertite", third:"si divertono" }}},
    { id: 175, it: "congratularsi con qcn.", pl: "gratulować komuś", presentIndicative: { singular: { first: "mi congratulo con qcn.", second: "ti congratuli con qcn.", third: "si congratula con qcn." }, plural: { first: "ci congratuliamo con qcn.", second: "vi congratulate con qcn.", third:"si congratulano con qcn." }}},
    { id: 176, it: "fidarsi di qcn.", pl: "ufać komuś", presentIndicative: { singular: { first: "mi fido di qcn.", second: "ti fidi di qcn.", third: "si fida di qcn." }, plural: { first: "ci fidiamo di qcn.", second: "vi fidate di qcn.", third:"si fidano di qcn." }}},
    { id: 177, it: "pentirsi di qcs.", pl: "żałować czegoś", presentIndicative: { singular: { first: "mi pento di qcs.", second: "ti penti di qcs.", third: "si pente di qcs." }, plural: { first: "ci pentiamo di qcs.", second: "vi pentite di qcs.", third:"si pentono di qcs." }}},
    { id: 178, it: "riposare/riposarsi", pl: "odpoczywać", presentIndicative: { singular: { first: "mi riposo", second: "ti riposi", third: "si riposa" }, plural: { first: "ci riposiamo", second: "vi riposate", third:"si riposano" }}},
    { id: 179, it: "annoiarsi", pl: "nudzić się", presentIndicative: { singular: { first: "mi annoio", second: "ti annoi", third: "si annoia" }, plural: { first: "ci annoiamo", second: "vi annoiate", third:"si annoiano" }}},
    { id: 180, it: "arrabbiarsi", pl: "rozgniewać się, rozzłościć się", presentIndicative: { singular: { first: "mi arrabbio", second: "ti arrabbii", third: "si arrabbia" }, plural: { first: "ci arrabbiamo", second: "vi arrabbiate", third:"si arrabbiano" }}},
]
const irregular: Card[] = [
    { id: 181, it: "essere", pl: "być", presentIndicative: { singular: { first: "sono", second: "sei", third: "è" }, plural: { first: "siamo", second: "siete", third:"sono" }}},
    { id: 182, it: "avere", pl: "mieć", presentIndicative: { singular: { first: "ho", second: "hai", third: "ha" }, plural: { first: "abbiamo", second: "avete", third:"hanno" }}},
    { id: 183, it: "volere", pl: "chcieć", presentIndicative: { singular: { first: "voglio", second: "vuoi", third: "vuole" }, plural: { first: "vogliamo", second: "volete", third:"vogliono" }}},
    { id: 184, it: "potere", pl: "móc", presentIndicative: { singular: { first: "posso", second: "puoi", third: "può" }, plural: { first: "possiamo", second: "potete", third:"possono" }}},
    { id: 185, it: "dovere", pl: "musieć, powinno się", presentIndicative: { singular: { first: "devo", second: "devi", third: "deve" }, plural: { first: "dobbiamo", second: "dovete", third:"devono" }}},
    { id: 186, it: "sapere", pl: "umieć, znać, wiedzieć", presentIndicative: { singular: { first: "so", second: "sai", third: "sa" }, plural: { first: "sappiamo", second: "sapete", third:"sanno" }}},
    { id: 187, it: "stare", pl: "czuć się", presentIndicative: { singular: { first: "sto", second: "stai", third: "sta" }, plural: { first: "stiamo", second: "state", third:"stanno" }}},
    { id: 188, it: "fare", pl: "robić", presentIndicative: { singular: { first: "faccio", second: "fai", third: "fa" }, plural: { first: "facciamo", second: "fate", third:"fanno" }}},
    { id: 189, it: "andare", pl: "iść, jechać", presentIndicative: { singular: { first: "vado", second: "vai", third: "va" }, plural: { first: "andiamo", second: "andate", third:"vanno" }}},
    { id: 190, it: "uscire", pl: "wychodzić", presentIndicative: { singular: { first: "esco", second: "esci", third: "esce" }, plural: { first: "usciamo", second: "uscite", third:"escono" }}},
    { id: 191, it: "bere", pl: "pić", presentIndicative: { singular: { first: "bevo", second: "bevi", third: "beve" }, plural: { first: "beviamo", second: "bevete", third:"bevono" }}},
    { id: 192, it: "dare", pl: "dawać", presentIndicative: { singular: { first: "do", second: "dai", third: "dà" }, plural: { first: "diamo", second: "date", third:"danno" }}},
    { id: 193, it: "dire", pl: "mówić", presentIndicative: { singular: { first: "dico", second: "dici", third: "dice" }, plural: { first: "diciamo", second: "dite", third:"dicono" }}},
    { id: 194, it: "tradurre", pl: "tłumaczyć", presentIndicative: { singular: { first: "traduco", second: "traduci", third: "traduce" }, plural: { first: "traduciamo", second: "traducete", third:"traducono" }}},
    { id: 195, it: "morire", pl: "umierać", presentIndicative: { singular: { first: "muoio", second: "muori", third: "muore" }, plural: { first: "moriamo", second: "morite", third:"muoiono" }}},
    { id: 196, it: "cuocere", pl: "gotować, piec", presentIndicative: { singular: { first: "cuocio", second: "cuoci", third: "cuoce" }, plural: { first: "cuociamo", second: "cuocete", third:"cuociono" }}},
    { id: 197, it: "sciare", pl: "jeździć na nartach", presentIndicative: { singular: { first: "scio", second: "scii", third: "scia" }, plural: { first: "sciamo", second: "sciate", third:"sciano" }}},
    { id: 198, it: "giocare", pl: "grać (w grę)", presentIndicative: { singular: { first: "gioco", second: "giochi", third: "gioca" }, plural: { first: "giochiamo", second: "giocate", third:"giocano" }}},
    { id: 199, it: "cercare", pl: "szukać", presentIndicative: { singular: { first: "cerco", second: "cerchi", third: "cerca" }, plural: { first: "cerchiamo", second: "cercate", third:"cercano" }}},
    { id: 200, it: "toccare", pl: "dotykać", presentIndicative: { singular: { first: "tocco", second: "tocchi", third: "tocca" }, plural: { first: "tocchiamo", second: "toccate", third:"toccano" }}},
    { id: 201, it: "spiegare", pl: "wyjaśniać", presentIndicative: { singular: { first: "spiego", second: "spieghi", third: "spiega" }, plural: { first: "spieghiamo", second: "spiegate", third:"spiegano" }}},
    { id: 202, it: "pagare", pl: "płacić", presentIndicative: { singular: { first: "pago", second: "paghi", third: "paga" }, plural: { first: "paghiamo", second: "pagate", third:"pagano" }}},
    { id: 203, it: "venire", pl: "przychodzić", presentIndicative: { singular: { first: "vengo", second: "vieni", third: "viene" }, plural: { first: "veniamo", second: "venite", third:"vengono" }}},
    { id: 204, it: "salire", pl: "wychodzić, iść w górę", presentIndicative: { singular: { first: "salgo", second: "sali", third: "sale" }, plural: { first: "saliamo", second: "salite", third:"salgono" }}},
    { id: 205, it: "rimanere", pl: "zostawać (o czasie)", presentIndicative: { singular: { first: "rimango", second: "rimani", third: "rimane" }, plural: { first: "rimaniamo", second: "rimanete", third:"rimangono" }}},
    { id: 206, it: "sedere; sedersi", pl: "siedzieć; siadać", presentIndicative: { singular: { first: "mi siedo; mi seggo", second: "ti siedi", third: "si siede" }, plural: { first: "ci sediamo", second: "vi sedete", third:"si siedono; si seggono" }}},
    { id: 207, it: "innervosire", pl: "denerwować się", presentIndicative: { singular: { first: "mi innervosisco", second: "ti innervosisci", third: "si innervosisce" }, plural: { first: "ci innervosiamo", second: "vi innervosite", third:"si innervosiscono" }}},
    { id: 208, it: "piacere", pl: "podobać się", presentIndicative: { singular: { first: "mi piace", second: "ti piace", third: "gli piace" }, plural: { first: "ci piace", second: "vi piace", third:"gli piace" }}},
    { id: 209, it: "dispiacere", pl: "być przykro", presentIndicative: { singular: { first: "mi dispiace", second: "ti dispiace", third: "gli dispiace" }, plural: { first: "ci dispiace", second: "vi dispiace", third:"gli dispiace" }}},
    { id: 210, it: "mancare", pl: "brakować", presentIndicative: { singular: { first: "mi manca", second: "ti manca", third: "gli manca" }, plural: { first: "ci manca", second: "vi manca", third:"gli manca" }}},
    { id: 211, it: "interessare; interessarsi", pl: "dotyczyć, interesować; interesować się", presentIndicative: { singular: { first: "mi interessa", second: "ti interessa", third: "gli interessa" }, plural: { first: "ci interessa", second: "vi interessa", third:"gli interessa" }}},
    { id: 212, it: "svegliare; svegliarsi", pl: "budzić; budzić się", presentIndicative: { singular: { first: "mi sveglio", second: "ti sveglii", third: "si sveglia" }, plural: { first: "ci svegliiamo", second: "vi svegliate", third:"si svegliano" }}},
    { id: 213, it: "fabbricare", pl: "wytwarzać, produkować", presentIndicative: { singular: { first: "fabbrico", second: "fabbrichi", third: "fabbrica" }, plural: { first: "fabbrichiamo", second: "fabbricate", third:"fabbricano" }}},
    { id: 214, it: "edificare", pl: "budować", presentIndicative: { singular: { first: "edifico", second: "edifichi", third: "edifica" }, plural: { first: "edifichiamo", second: "edificate", third:"edificano" }}},
    { id: 215, it: "pregare", pl: "prosić", presentIndicative: { singular: { first: "prego", second: "preghi", third: "prega" }, plural: { first: "preghiamo", second: "pregate", third:"pregano" }}},
    { id: 216, it: "dimenticare; dimenticarsi", pl: "zapominać; zapominać się (?)", presentIndicative: { singular: { first: "dimentico", second: "dimentichi", third: "dimentica" }, plural: { first: "dimentichiamo", second: "dimenticate", third:"dimenticano" }}},
    { id: 217, it: "nevicare", pl: "padać (o śniegu)", presentIndicative: { singular: { first: "nevico", second: "nevichi", third: "nevica" }, plural: { first: "nevichiamo", second: "nevicate", third:"nevicano" }}},
    { id: 218, it: "stancare; stancarsi", pl: "męczyć; zmęczyć się", presentIndicative: { singular: { first: "stanco", second: "stanchi", third: "stanca" }, plural: { first: "stanchiamo", second: "stancate", third:"stancano" }}},
    { id: 219, it: "sporcare; sporcarsi", pl: "brudzić; brudzić się", presentIndicative: { singular: { first: "sporco", second: "sporchi", third: "sporca" }, plural: { first: "sporchiamo", second: "sporcate", third:"sporcano" }}},
    { id: 220, it: "togliere", pl: "zdejmować, usuwać", presentIndicative: { singular: { first: "tolgo", second: "togli", third: "toglie" }, plural: { first: "togliamo", second: "togliete", third:"tolgono" }}},
    { id: 221, it: "proporre", pl: "proponować", presentIndicative: { singular: { first: "propongo", second: "proponi", third: "propone" }, plural: { first: "proponiamo", second: "proponete", third:"propongono" }}},
    { id: 222, it: "scegliere", pl: "wybierać", presentIndicative: { singular: { first: "scelgo", second: "scegli", third: "sceglie" }, plural: { first: "scegliamo", second: "scegliete", third:"scelgono" }}},
    { id: 223, it: "tenere", pl: "trzymać", presentIndicative: { singular: { first: "tengo", second: "tieni", third: "tiene" }, plural: { first: "teniamo", second: "tenete", third:"tengono" }}},
]
const newOrHard: Card[] = [
    { id: 1, it: "diventare", pl: "stawać się, zostawać", presentIndicative: { singular: { first: "divento", second: "diventi", third: "diventa" }, plural: { first: "diventiamo", second: "diventate", third:"diventano" }}},
    { id: 3, it: "imparare", pl: "uczyć się", presentIndicative: { singular: { first: "imparo", second: "impari", third: "impara" }, plural: { first: "impariamo", second: "imparate", third:"imparano" }}},
    { id: 9, it: "ascoltare", pl: "słuchać", presentIndicative: { singular: { first: "ascolto", second: "ascolti", third: "ascolta" }, plural: { first: "ascoltiamo", second: "ascoltate", third:"ascoltano" }}},
    { id: 13, it: "portare", pl: "nieść, nosić, przynosić, przyprowadzać", presentIndicative: { singular: { first: "porto", second: "porti", third: "porta" }, plural: { first: "portiamo", second: "portate", third:"portano" }}},
    { id: 14, it: "tornare", pl: "wracać", presentIndicative: { singular: { first: "torno", second: "torni", third: "torna" }, plural: { first: "torniamo", second: "tornate", third:"tornano" }}},
    { id: 23, it: "ordinare", pl: "porządkować, rozkazywać, zamawiać", presentIndicative: { singular: { first: "ordino", second: "ordini", third: "ordina" }, plural: { first: "ordiniamo", second: "ordinate", third:"ordinano" }}},
    { id: 28, it: "incontrare; incontrarsi", pl: "spotykać; spotykać się", presentIndicative: { singular: { first: "incontro", second: "incontri", third: "incontra" }, plural: { first: "incontriamo", second: "incontrate", third:"incontrano" }}},
    { id: 34, it: "sperare", pl: "mieć nadzieję", presentIndicative: { singular: { first: "spero", second: "speri", third: "spera" }, plural: { first: "speriamo", second: "sperate", third:"sperano" }}},
    { id: 37, it: "aspettare", pl: "czekać, oczekiwać na kogoś/coś", presentIndicative: { singular: { first: "aspetto", second: "aspetti", third: "aspetta" }, plural: { first: "aspettiamo", second: "aspettate", third:"aspettano" }}},
    { id: 40, it: "guadagnare", pl: "zarabiać", presentIndicative: { singular: { first: "guadagno", second: "guadagni", third: "guadagna" }, plural: { first: "guadagniamo", second: "guadagnate", third:"guadagnano" }}},
    { id: 41, it: "passare", pl: "mijać, spędzać (czas)", presentIndicative: { singular: { first: "passo", second: "passi", third: "passa" }, plural: { first: "passiamo", second: "passate", third:"passano" }}},
    { id: 42, it: "suonare", pl: "dzwonić, grać (na instrumencie)", presentIndicative: { singular: { first: "suono", second: "suoni", third: "suona" }, plural: { first: "suoniamo", second: "suonate", third:"suonano" }}},
    { id: 43, it: "bussare", pl: "pukać", presentIndicative: { singular: { first: "busso", second: "bussi", third: "bussa" }, plural: { first: "bussiamo", second: "bussate", third:"bussano" }}},
    { id: 44, it: "prestare", pl: "pożyczać", presentIndicative: { singular: { first: "presto", second: "presti", third: "presta" }, plural: { first: "prestiamo", second: "prestate", third:"prestano" }}},
    { id: 45, it: "formare", pl: "formować, tworzyć", presentIndicative: { singular: { first: "formo", second: "formi", third: "forma" }, plural: { first: "formiamo", second: "formate", third:"formano" }}},
    { id: 46, it: "pettinare; pettinarsi", pl: "czesać; czesać się", presentIndicative: { singular: { first: "pettino", second: "pettini", third: "pettina" }, plural: { first: "pettiniamo", second: "pettinate", third:"pettinano" }}},
    { id: 47, it: "bagnare", pl: "moczyć, zmoczyć", presentIndicative: { singular: { first: "bagno", second: "bagni", third: "bagna" }, plural: { first: "bagniamo", second: "bagnate", third:"bagnano" }}},
    { id: 48, it: "disegnare", pl: "rysować", presentIndicative: { singular: { first: "disegno", second: "disegni", third: "disegna" }, plural: { first: "disegniamo", second: "disegnate", third:"disegnano" }}},
    { id: 49, it: "mostrare", pl: "pokazywać", presentIndicative: { singular: { first: "mostro", second: "mostri", third: "mostra" }, plural: { first: "mostriamo", second: "mostrate", third:"mostrano" }}},
    { id: 50, it: "indirizzare", pl: "adresować", presentIndicative: { singular: { first: "indirizzo", second: "indirizzi", third: "indirizza" }, plural: { first: "indirizziamo", second: "indirizzate", third:"indirizzano" }}},
    { id: 51, it: "informare", pl: "informować", presentIndicative: { singular: { first: "informo", second: "informi", third: "informa" }, plural: { first: "informiamo", second: "informate", third:"informano" }}},
    { id: 52, it: "registrare", pl: "nagrywać", presentIndicative: { singular: { first: "registro", second: "registri", third: "registra" }, plural: { first: "registriamo", second: "registrate", third:"registrano" }}},
    { id: 53, it: "provare", pl: "przymierzać", presentIndicative: { singular: { first: "provo", second: "provi", third: "prova" }, plural: { first: "proviamo", second: "provate", third:"provano" }}},
    { id: 54, it: "presentare", pl: "przedstawiać, prezentować", presentIndicative: { singular: { first: "presento", second: "presenti", third: "presenta" }, plural: { first: "presentiamo", second: "presentate", third:"presentano" }}},
    { id: 55, it: "osservare", pl: "obserwować", presentIndicative: { singular: { first: "osservo", second: "osservi", third: "osserva" }, plural: { first: "osserviamo", second: "osservate", third:"osservano" }}},
    { id: 56, it: "insegnare", pl: "uczyć (kogoś)", presentIndicative: { singular: { first: "insegno", second: "insegni", third: "insegna" }, plural: { first: "insegniamo", second: "insegnate", third:"insegnano" }}},
    { id: 57, it: "domandare", pl: "pytać", presentIndicative: { singular: { first: "domando", second: "domandi", third: "domanda" }, plural: { first: "domandiamo", second: "domandate", third:"domandano" }}},
    { id: 58, it: "frequentare", pl: "chodzić; uczęszczać", presentIndicative: { singular: { first: "frequento", second: "frequenti", third: "frequenta" }, plural: { first: "frequentiamo", second: "frequentate", third:"frequentano" }}},
    { id: 59, it: "salare", pl: "solić", presentIndicative: { singular: { first: "salo", second: "sali", third: "sala" }, plural: { first: "saliamo", second: "salate", third:"salano" }}},
    { id: 60, it: "zuccherare", pl: "słodzić", presentIndicative: { singular: { first: "zucchero", second: "zuccheri", third: "zucchera" }, plural: { first: "zuccheriamo", second: "zuccherate", third:"zuccherano" }}},
    { id: 61, it: "confinare", pl: "graniczyć", presentIndicative: { singular: { first: "confino", second: "confini", third: "confina" }, plural: { first: "confiniamo", second: "confinate", third:"confinano" }}},
    { id: 62, it: "arrivare", pl: "przyjeżdżać, przybywać", presentIndicative: { singular: { first: "arrivo", second: "arrivi", third: "arriva" }, plural: { first: "arriviamo", second: "arrivate", third:"arrivano" }}},
    { id: 63, it: "ritornare", pl: "wracać (znowu?)", presentIndicative: { singular: { first: "ritorno", second: "ritorni", third: "ritorna" }, plural: { first: "ritorniamo", second: "ritornate", third:"ritornano" }}},
    { id: 64, it: "organizzare", pl: "organizować", presentIndicative: { singular: { first: "organizzo", second: "organizzi", third: "organizza" }, plural: { first: "organizziamo", second: "organizzate", third:"organizzano" }}},
    { id: 65, it: "bisognare", pl: "musieć (3 os. lp.), trzeba", presentIndicative: { singular: { first: "bisogno", second: "bisogni", third: "bisogna" }, plural: { first: "bisogniamo", second: "bisognate", third:"bisognano" }}},
    { id: 66, it: "rubare", pl: "kraść", presentIndicative: { singular: { first: "rubo", second: "rubi", third: "ruba" }, plural: { first: "rubiamo", second: "rubate", third:"rubano" }}},
    { id: 67, it: "regalare", pl: "podarować", presentIndicative: { singular: { first: "regalo", second: "regali", third: "regala" }, plural: { first: "regaliamo", second: "regalate", third:"regalano" }}},
    { id: 68, it: "sposare; sposarsi", pl: "poślubić (kogoś); brać ślub", presentIndicative: { singular: { first: "sposo", second: "sposi", third: "sposa" }, plural: { first: "sposiamo", second: "sposate", third:"sposano" }}},
    { id: 69, it: "restare", pl: "zostawać (o miejscu)", presentIndicative: { singular: { first: "resto", second: "resti", third: "resta" }, plural: { first: "restiamo", second: "restate", third:"restano" }}},
    { id: 70, it: "girare", pl: "skręcać", presentIndicative: { singular: { first: "giro", second: "giri", third: "gira" }, plural: { first: "giriamo", second: "girate", third:"girano" }}},
    { id: 71, it: "esercitare", pl: "ćwiczyć", presentIndicative: { singular: { first: "esercito", second: "eserciti", third: "esercita" }, plural: { first: "esercitiamo", second: "esercitate", third:"esercitano" }}},
    { id: 72, it: "raccontare", pl: "opowiadać", presentIndicative: { singular: { first: "racconto", second: "racconti", third: "racconta" }, plural: { first: "raccontiamo", second: "raccontate", third:"raccontano" }}},
    { id: 73, it: "guidare", pl: "kierować, prowadzić (auto)", presentIndicative: { singular: { first: "guido", second: "guidi", third: "guida" }, plural: { first: "guidiamo", second: "guidate", third:"guidano" }}},
    { id: 74, it: "ritardare", pl: "spóźniać się", presentIndicative: { singular: { first: "ritardo", second: "ritardi", third: "ritarda" }, plural: { first: "ritardiamo", second: "ritardate", third:"ritardano" }}},
    { id: 75, it: "detestare", pl: "nienawidzić, nie cierpieć", presentIndicative: { singular: { first: "detesto", second: "detesti", third: "detesta" }, plural: { first: "detestiamo", second: "detestate", third:"detestano" }}},
    { id: 76, it: "compilare", pl: "wypełniać (np. formularz)", presentIndicative: { singular: { first: "compilo", second: "compili", third: "compila" }, plural: { first: "compiliamo", second: "compilate", third:"compilano" }}},
    { id: 77, it: "sottolineare", pl: "podkreślać", presentIndicative: { singular: { first: "sottolineo", second: "sottolinei", third: "sottolinea" }, plural: { first: "sottolineiamo", second: "sottolineate", third:"sottolineano" }}},
    { id: 78, it: "segnare", pl: "zaznaczać", presentIndicative: { singular: { first: "segno", second: "segni", third: "segna" }, plural: { first: "segniamo", second: "segnate", third:"segnano" }}},
    { id: 79, it: "firmare", pl: "podpisywać", presentIndicative: { singular: { first: "firmo", second: "firmi", third: "firma" }, plural: { first: "firmiamo", second: "firmate", third:"firmano" }}},
    { id: 80, it: "timbrare", pl: "postawić pieczątkę", presentIndicative: { singular: { first: "timbro", second: "timbri", third: "timbra" }, plural: { first: "timbriamo", second: "timbrate", third:"timbrano" }}},
    { id: 81, it: "scappare", pl: "uciekać", presentIndicative: { singular: { first: "scappo", second: "scappi", third: "scappa" }, plural: { first: "scappiamo", second: "scappate", third:"scappano" }}},
    { id: 82, it: "fumare", pl: "palić (papierosy)", presentIndicative: { singular: { first: "fumo", second: "fumi", third: "fuma" }, plural: { first: "fumiamo", second: "fumate", third:"fumano" }}},
    { id: 83, it: "raffreddare; raffreddarsi", pl: "chłodzić; przeziębić się", presentIndicative: { singular: { first: "raffreddo", second: "raffreddi", third: "raffredda" }, plural: { first: "raffreddiamo", second: "raffreddate", third:"raffreddano" }}},
    { id: 84, it: "chiamare", pl: "wzywać, wołać", presentIndicative: { singular: { first: "chiamo", second: "chiami", third: "chiama" }, plural: { first: "chiamiamo", second: "chiamate", third:"chiamano" }}},
    { id: 85, it: "volare", pl: "latać, fruwać", presentIndicative: { singular: { first: "volo", second: "voli", third: "vola" }, plural: { first: "voliamo", second: "volate", third:"volano" }}},
    { id: 86, it: "preparare; prepararsi", pl: "przygotowywać; przygotowywać się", presentIndicative: { singular: { first: "preparo", second: "prepari", third: "prepara" }, plural: { first: "prepariamo", second: "preparate", third:"preparano" }}},
    { id: 87, it: "funzionare", pl: "działać, funkcjonować", presentIndicative: { singular: { first: "funziono", second: "funzioni", third: "funziona" }, plural: { first: "funzioniamo", second: "funzionate", third:"funzionano" }}},
    { id: 88, it: "mangiare", pl: "jeść", presentIndicative: { singular: { first: "mangio", second: "mangi", third: "mangia" }, plural: { first: "mangiamo", second: "mangiate", third:"mangiano" }}},
    { id: 90, it: "lasciare", pl: "zostawiać, opuszczać", presentIndicative: { singular: { first: "lascio", second: "lasci", third: "lascia" }, plural: { first: "lasciamo", second: "lasciate", third:"lasciano" }}},
    { id: 92, it: "cominciare", pl: "zaczynać (się)", presentIndicative: { singular: { first: "comincio", second: "cominci", third: "comincia" }, plural: { first: "cominciamo", second: "cominciate", third:"cominciano" }}},
    { id: 93, it: "risparmiare", pl: "oszczędzać", presentIndicative: { singular: { first: "risparmio", second: "risparmi", third: "risparmia" }, plural: { first: "risparmiamo", second: "risparmiate", third:"risparmiano" }}},
    { id: 94, it: "parcheggiare", pl: "parkować", presentIndicative: { singular: { first: "parcheggio", second: "parcheggi", third: "parcheggia" }, plural: { first: "parcheggiamo", second: "parcheggiate", third:"parcheggiano" }}},
    { id: 95, it: "spogliare; spogliarsi", pl: "rozbierać; rozbierać się", presentIndicative: { singular: { first: "spoglio", second: "spogli", third: "spoglia" }, plural: { first: "spogliamo", second: "spogliate", third:"spogliano" }}},
    { id: 96, it: "cambiare; cambiarsi", pl: "zamieniać, wymieniać; przebierać się", presentIndicative: { singular: { first: "cambio", second: "cambi", third: "cambia" }, plural: { first: "cambiamo", second: "cambiate", third:"cambiano" }}},
    { id: 97, it: "tagliare", pl: "kroić, ciąć", presentIndicative: { singular: { first: "taglio", second: "tagli", third: "taglia" }, plural: { first: "tagliamo", second: "tagliate", third:"tagliano" }}},
    { id: 98, it: "viaggiare", pl: "podróżować", presentIndicative: { singular: { first: "viaggio", second: "viaggi", third: "viaggia" }, plural: { first: "viaggiamo", second: "viaggiate", third:"viaggiano" }}},
    { id: 99, it: "sbagliare", pl: "mylić się", presentIndicative: { singular: { first: "sbaglio", second: "sbagli", third: "sbaglia" }, plural: { first: "sbagliamo", second: "sbagliate", third:"sbagliano" }}},
    { id: 100, it: "lanciare", pl: "rzucać", presentIndicative: { singular: { first: "lancio", second: "lanci", third: "lancia" }, plural: { first: "lanciamo", second: "lanciate", third:"lanciano" }}},
    { id: 101, it: "calciare", pl: "kopać (np. piłkę)", presentIndicative: { singular: { first: "calcio", second: "calci", third: "calcia" }, plural: { first: "calciamo", second: "calciate", third:"calciano" }}},
    { id: 102, it: "passeggiare", pl: "spacerować", presentIndicative: { singular: { first: "passegio", second: "passegi", third: "passegia" }, plural: { first: "passegiamo", second: "passegiate", third:"passegiano" }}},
    { id: 103, it: "prendere", pl: "brać, kupować, jeść, pić", presentIndicative: { singular: { first: "prendo", second: "prendi", third: "prende" }, plural: { first: "prendiamo", second: "prendete", third:"prendono" }}},
    { id: 105, it: "vedere; vedersi", pl: "widzieć; widzieć się", presentIndicative: { singular: { first: "vedo", second: "vedi", third: "vede" }, plural: { first: "vediamo", second: "vedete", third:"vedono" }}},
    { id: 107, it: "chiedere", pl: "pytać, prosić", presentIndicative: { singular: { first: "chiedo", second: "chiedi", third: "chiede" }, plural: { first: "chiediamo", second: "chiedete", third:"chiedono" }}},
    { id: 114, it: "scendere", pl: "schodzić, wysiadać", presentIndicative: { singular: { first: "scendo", second: "scendi", third: "scende" }, plural: { first: "scendiamo", second: "scendete", third:"scendono" }}},
    { id: 119, it: "chiudere", pl: "zamykać", presentIndicative: { singular: { first: "chiudo", second: "chiudi", third: "chiude" }, plural: { first: "chiudiamo", second: "chiudete", third:"chiudono" }}},
    { id: 120, it: "spingere", pl: "pchać", presentIndicative: { singular: { first: "spingo", second: "spingi", third: "spinge" }, plural: { first: "spingiamo", second: "spingete", third:"spingono" }}},
    { id: 121, it: "accendere", pl: "włączać, zapalać", presentIndicative: { singular: { first: "accendo", second: "accendi", third: "accende" }, plural: { first: "accendiamo", second: "accendete", third:"accendono" }}},
    { id: 123, it: "godere", pl: "cieszyć się czymś, korzystać z czegoś", presentIndicative: { singular: { first: "godo", second: "godi", third: "gode" }, plural: { first: "godiamo", second: "godete", third:"godono" }}},
    { id: 126, it: "conoscere; conoscersi", pl: "znać; znać się", presentIndicative: { singular: { first: "conosco", second: "conosci", third: "conosce" }, plural: { first: "conosciamo", second: "conoscete", third:"conoscono" }}},
    { id: 127, it: "proteggere", pl: "chronić", presentIndicative: { singular: { first: "proteggo", second: "proteggi", third: "protegge" }, plural: { first: "proteggiamo", second: "proteggete", third:"proteggono" }}},
    { id: 128, it: "distruggere", pl: "niszczyć", presentIndicative: { singular: { first: "distruggo", second: "distruggi", third: "distrugge" }, plural: { first: "distruggiamo", second: "distruggete", third:"distruggono" }}},
    { id: 129, it: "spendere", pl: "wydawać (pieniądze)", presentIndicative: { singular: { first: "spendo", second: "spendi", third: "spende" }, plural: { first: "spendiamo", second: "spendete", third:"spendono" }}},
    { id: 130, it: "dipingere", pl: "malować", presentIndicative: { singular: { first: "dipingo", second: "dipingi", third: "dipinge" }, plural: { first: "dipingiamo", second: "dipingete", third:"dipingono" }}},
    { id: 131, it: "descrivere", pl: "opisywać", presentIndicative: { singular: { first: "descrivo", second: "descrivi", third: "descrive" }, plural: { first: "descriviamo", second: "descrivete", third:"descrivono" }}},
    { id: 132, it: "correggere", pl: "sprawdzać, poprawiać", presentIndicative: { singular: { first: "correggo", second: "correggi", third: "corregge" }, plural: { first: "correggiamo", second: "correggete", third:"correggono" }}},
    { id: 133, it: "piovere", pl: "padać (o deszczu)", presentIndicative: { singular: { first: "piovo", second: "piovi", third: "piove" }, plural: { first: "pioviamo", second: "piovete", third:"piovono" }}},
    { id: 134, it: "uccidere", pl: "zabijać", presentIndicative: { singular: { first: "uccido", second: "uccidi", third: "uccide" }, plural: { first: "uccidiamo", second: "uccidete", third:"uccidono" }}},
    { id: 135, it: "ricevere", pl: "dostawać, otrzymywać", presentIndicative: { singular: { first: "ricevo", second: "ricevi", third: "riceve" }, plural: { first: "riceviamo", second: "ricevete", third:"ricevono" }}},
    { id: 136, it: "cadere", pl: "upadać, spadać", presentIndicative: { singular: { first: "cado", second: "cadi", third: "cade" }, plural: { first: "cadiamo", second: "cadete", third:"cadono" }}},
    { id: 137, it: "ridere", pl: "śmiać się", presentIndicative: { singular: { first: "rido", second: "ridi", third: "ride" }, plural: { first: "ridiamo", second: "ridete", third:"ridono" }}},
    { id: 138, it: "sorridere", pl: "uśmiechać się", presentIndicative: { singular: { first: "sorrido", second: "sorridi", third: "sorride" }, plural: { first: "sorridiamo", second: "sorridete", third:"sorridono" }}},
    { id: 139, it: "sorprendere", pl: "zaskakiwać, dziwić", presentIndicative: { singular: { first: "sorprendo", second: "sorprendi", third: "sorprende" }, plural: { first: "sorprendiamo", second: "sorprendete", third:"sorprendono" }}},
    { id: 140, it: "permettere", pl: "pozwalać, zezwalać", presentIndicative: { singular: { first: "permetto", second: "permetti", third: "permette" }, plural: { first: "permettiamo", second: "permettete", third:"permettono" }}},
    { id: 141, it: "battere", pl: "bić, uderzać", presentIndicative: { singular: { first: "batto", second: "batti", third: "batte" }, plural: { first: "battiamo", second: "battete", third:"battono" }}},
    { id: 142, it: "piangere", pl: "płakać", presentIndicative: { singular: { first: "piango", second: "piangi", third: "piange" }, plural: { first: "piangiamo", second: "piangete", third:"piangono" }}},
    { id: 146, it: "coprire", pl: "przykrywać", presentIndicative: { singular: { first: "copro", second: "copri", third: "copre" }, plural: { first: "copriamo", second: "coprite", third:"coprono" }}},
    { id: 147, it: "scoprire", pl: "odkrywać", presentIndicative: { singular: { first: "scopro", second: "scopri", third: "scopre" }, plural: { first: "scopriamo", second: "scoprite", third:"scoprono" }}},
    { id: 154, it: "dimagrire", pl: "chudnąć", presentIndicative: { singular: { first: "dimagrisco", second: "dimagrisci", third: "dimagrisce" }, plural: { first: "dimagriamo", second: "dimagrite", third:"dimagriscono" }}},
    { id: 159, it: "restituire", pl: "zwracać, oddawać", presentIndicative: { singular: { first: "restituisco", second: "restituisci", third: "restituisce" }, plural: { first: "restituiamo", second: "restituite", third:"restituiscono" }}},
    { id: 160, it: "spedire", pl: "wysyłać (pocztą)", presentIndicative: { singular: { first: "spedisco", second: "spedisci", third: "spedisce" }, plural: { first: "spediamo", second: "spedite", third:"spediscono" }}},
    { id: 165, it: "scusarsi", pl: "przeprosić, przepraszać", presentIndicative: { singular: { first: "mi scuso", second: "ti scusi", third: "si scusa" }, plural: { first: "ci scusiamo", second: "vi scusate", third:"si scusano" }}},
    { id: 166, it: "abituarsi", pl: "przyzwyczaić się", presentIndicative: { singular: { first: "mi abituo", second: "ti abitui", third: "si abitua" }, plural: { first: "ci abituiamo", second: "vi abituate", third:"si abituano" }}},
    { id: 167, it: "alzarsi", pl: "wstawać", presentIndicative: { singular: { first: "mi alzo", second: "ti alzi", third: "si alza" }, plural: { first: "ci alziamo", second: "vi alzate", third:"si alzano" }}},
    { id: 168, it: "ritrovarsi", pl: "odnaleźć się", presentIndicative: { singular: { first: "mi ritrovo", second: "ti ritrovi", third: "si ritrova" }, plural: { first: "ci ritroviamo", second: "vi ritrovate", third:"si ritrovano" }}},
    { id: 170, it: "addormentarsi", pl: "zasnąć", presentIndicative: { singular: { first: "mi addormento", second: "ti addormenti", third: "si addormenta" }, plural: { first: "ci addormentiamo", second: "vi addormentate", third:"si addormentano" }}},
    { id: 172, it: "esprimersi", pl: "wyrażać się", presentIndicative: { singular: { first: "mi esprimo", second: "ti esprimi", third: "si esprime" }, plural: { first: "ci esprimiamo", second: "vi esprimete", third:"si esprimono" }}},
    { id: 174, it: "divertirsi", pl: "bawić się, spędzać miło czas", presentIndicative: { singular: { first: "mi diverto", second: "ti diverti", third: "si diverte" }, plural: { first: "ci divertiamo", second: "vi divertite", third:"si divertono" }}},
    { id: 178, it: "riposare/riposarsi", pl: "odpoczywać", presentIndicative: { singular: { first: "mi riposo", second: "ti riposi", third: "si riposa" }, plural: { first: "ci riposiamo", second: "vi riposate", third:"si riposano" }}},
    { id: 179, it: "annoiarsi", pl: "nudzić się", presentIndicative: { singular: { first: "mi annoio", second: "ti annoi", third: "si annoia" }, plural: { first: "ci annoiamo", second: "vi annoiate", third:"si annoiano" }}},
    { id: 180, it: "arrabbiarsi", pl: "rozgniewać się, rozzłościć się", presentIndicative: { singular: { first: "mi arrabbio", second: "ti arrabbii", third: "si arrabbia" }, plural: { first: "ci arrabbiamo", second: "vi arrabbiate", third:"si arrabbiano" }}},
    { id: 181, it: "essere", pl: "być", presentIndicative: { singular: { first: "sono", second: "sei", third: "è" }, plural: { first: "siamo", second: "siete", third:"sono" }}},
    { id: 182, it: "avere", pl: "mieć", presentIndicative: { singular: { first: "ho", second: "hai", third: "ha" }, plural: { first: "abbiamo", second: "avete", third:"hanno" }}},
    { id: 183, it: "volere", pl: "chcieć", presentIndicative: { singular: { first: "voglio", second: "vuoi", third: "vuole" }, plural: { first: "vogliamo", second: "volete", third:"vogliono" }}},
    { id: 184, it: "potere", pl: "móc", presentIndicative: { singular: { first: "posso", second: "puoi", third: "può" }, plural: { first: "possiamo", second: "potete", third:"possono" }}},
    { id: 185, it: "dovere", pl: "musieć, powinno się", presentIndicative: { singular: { first: "devo", second: "devi", third: "deve" }, plural: { first: "dobbiamo", second: "dovete", third:"devono" }}},
    { id: 186, it: "sapere", pl: "umieć, znać, wiedzieć", presentIndicative: { singular: { first: "so", second: "sai", third: "sa" }, plural: { first: "sappiamo", second: "sapete", third:"sanno" }}},
    { id: 187, it: "stare", pl: "czuć się", presentIndicative: { singular: { first: "sto", second: "stai", third: "sta" }, plural: { first: "stiamo", second: "state", third:"stanno" }}},
    { id: 188, it: "fare", pl: "robić", presentIndicative: { singular: { first: "faccio", second: "fai", third: "fa" }, plural: { first: "facciamo", second: "fate", third:"fanno" }}},
    { id: 189, it: "andare", pl: "iść, jechać", presentIndicative: { singular: { first: "vado", second: "vai", third: "va" }, plural: { first: "andiamo", second: "andate", third:"vanno" }}},
    { id: 190, it: "uscire", pl: "wychodzić", presentIndicative: { singular: { first: "esco", second: "esci", third: "esce" }, plural: { first: "usciamo", second: "uscite", third:"escono" }}},
    { id: 191, it: "bere", pl: "pić", presentIndicative: { singular: { first: "bevo", second: "bevi", third: "beve" }, plural: { first: "beviamo", second: "bevete", third:"bevono" }}},
    { id: 192, it: "dare", pl: "dawać", presentIndicative: { singular: { first: "do", second: "dai", third: "dà" }, plural: { first: "diamo", second: "date", third:"danno" }}},
    { id: 193, it: "dire", pl: "mówić", presentIndicative: { singular: { first: "dico", second: "dici", third: "dice" }, plural: { first: "diciamo", second: "dite", third:"dicono" }}},
    { id: 194, it: "tradurre", pl: "tłumaczyć", presentIndicative: { singular: { first: "traduco", second: "traduci", third: "traduce" }, plural: { first: "traduciamo", second: "traducete", third:"traducono" }}},
    { id: 195, it: "morire", pl: "umierać", presentIndicative: { singular: { first: "muoio", second: "muori", third: "muore" }, plural: { first: "moriamo", second: "morite", third:"muoiono" }}},
    { id: 196, it: "cuocere", pl: "gotować, piec", presentIndicative: { singular: { first: "cuocio", second: "cuoci", third: "cuoce" }, plural: { first: "cuociamo", second: "cuocete", third:"cuociono" }}},
    { id: 197, it: "sciare", pl: "jeździć na nartach", presentIndicative: { singular: { first: "scio", second: "scii", third: "scia" }, plural: { first: "sciamo", second: "sciate", third:"sciano" }}},
    { id: 198, it: "giocare", pl: "grać (w grę)", presentIndicative: { singular: { first: "gioco", second: "giochi", third: "gioca" }, plural: { first: "giochiamo", second: "giocate", third:"giocano" }}},
    { id: 199, it: "cercare", pl: "szukać", presentIndicative: { singular: { first: "cerco", second: "cerchi", third: "cerca" }, plural: { first: "cerchiamo", second: "cercate", third:"cercano" }}},
    { id: 200, it: "toccare", pl: "dotykać", presentIndicative: { singular: { first: "tocco", second: "tocchi", third: "tocca" }, plural: { first: "tocchiamo", second: "toccate", third:"toccano" }}},
    { id: 201, it: "spiegare", pl: "wyjaśniać", presentIndicative: { singular: { first: "spiego", second: "spieghi", third: "spiega" }, plural: { first: "spieghiamo", second: "spiegate", third:"spiegano" }}},
    { id: 202, it: "pagare", pl: "płacić", presentIndicative: { singular: { first: "pago", second: "paghi", third: "paga" }, plural: { first: "paghiamo", second: "pagate", third:"pagano" }}},
    { id: 203, it: "venire", pl: "przychodzić", presentIndicative: { singular: { first: "vengo", second: "vieni", third: "viene" }, plural: { first: "veniamo", second: "venite", third:"vengono" }}},
    { id: 204, it: "salire", pl: "wychodzić, iść w górę", presentIndicative: { singular: { first: "salgo", second: "sali", third: "sale" }, plural: { first: "saliamo", second: "salite", third:"salgono" }}},
    { id: 205, it: "rimanere", pl: "zostawać (o czasie)", presentIndicative: { singular: { first: "rimango", second: "rimani", third: "rimane" }, plural: { first: "rimaniamo", second: "rimanete", third:"rimangono" }}},
    { id: 206, it: "sedere; sedersi", pl: "siedzieć; siadać", presentIndicative: { singular: { first: "mi siedo; mi seggo", second: "ti siedi", third: "si siede" }, plural: { first: "ci sediamo", second: "vi sedete", third:"si siedono; si seggono" }}},
    { id: 207, it: "innervosire", pl: "denerwować się", presentIndicative: { singular: { first: "mi innervosisco", second: "ti innervosisci", third: "si innervosisce" }, plural: { first: "ci innervosiamo", second: "vi innervosite", third:"si nnervosiscono" }}},
    { id: 208, it: "piacere", pl: "podobać się", presentIndicative: { singular: { first: "mi piace", second: "ti piace", third: "gli piace" }, plural: { first: "ci piace", second: "vi piace", third:"gli piace" }}},
    { id: 209, it: "dispiacere", pl: "być przykro", presentIndicative: { singular: { first: "mi dispiace", second: "ti dispiace", third: "gli dispiace" }, plural: { first: "ci dispiace", second: "vi dispiace", third:"gli dispiace" }}},
    { id: 210, it: "mancare", pl: "brakować", presentIndicative: { singular: { first: "mi manca", second: "ti manca", third: "gli manca" }, plural: { first: "ci manca", second: "vi manca", third:"gli manca" }}},
    { id: 211, it: "interessare; interessarsi", pl: "dotyczyć, interesować; interesować się", presentIndicative: { singular: { first: "mi interessa", second: "ti interessa", third: "gli interessa" }, plural: { first: "ci interessa", second: "vi interessa", third:"gli interessa" }}},
    { id: 212, it: "svegliare; svegliarsi", pl: "budzić; budzić się", presentIndicative: { singular: { first: "mi sveglio", second: "ti sveglii", third: "si sveglia" }, plural: { first: "ci svegliiamo", second: "vi svegliate", third:"si svegliano" }}},
    { id: 213, it: "fabbricare", pl: "wytwarzać, produkować", presentIndicative: { singular: { first: "fabbrico", second: "fabbrichi", third: "fabbrica" }, plural: { first: "fabbrichiamo", second: "fabbricate", third:"fabbricano" }}},
    { id: 214, it: "edificare", pl: "budować", presentIndicative: { singular: { first: "edifico", second: "edifichi", third: "edifica" }, plural: { first: "edifichiamo", second: "edificate", third:"edificano" }}},
    { id: 215, it: "pregare", pl: "prosić", presentIndicative: { singular: { first: "prego", second: "preghi", third: "prega" }, plural: { first: "preghiamo", second: "pregate", third:"pregano" }}},
    { id: 216, it: "dimenticare; dimenticarsi", pl: "zapominać; zapominać się (?)", presentIndicative: { singular: { first: "dimentico", second: "dimentichi", third: "dimentica" }, plural: { first: "dimentichiamo", second: "dimenticate", third:"dimenticano" }}},
    { id: 217, it: "nevicare", pl: "padać (o śniegu)", presentIndicative: { singular: { first: "nevico", second: "nevichi", third: "nevica" }, plural: { first: "nevichiamo", second: "nevicate", third:"nevicano" }}},
    { id: 218, it: "stancare; stancarsi", pl: "męczyć; zmęczyć się", presentIndicative: { singular: { first: "stanco", second: "stanchi", third: "stanca" }, plural: { first: "stanchiamo", second: "stancate", third:"stancano" }}},
    { id: 219, it: "sporcare; sporcarsi", pl: "brudzić; brudzić się", presentIndicative: { singular: { first: "sporco", second: "sporchi", third: "sporca" }, plural: { first: "sporchiamo", second: "sporcate", third:"sporcano" }}},
    { id: 220, it: "togliere", pl: "zdejmować, usuwać", presentIndicative: { singular: { first: "tolgo", second: "togli", third: "toglie" }, plural: { first: "togliamo", second: "togliete", third:"tolgono" }}},
    { id: 221, it: "proporre", pl: "proponować", presentIndicative: { singular: { first: "propongo", second: "proponi", third: "propone" }, plural: { first: "proponiamo", second: "proponete", third:"propongono" }}},
    { id: 222, it: "scegliere", pl: "wybierać", presentIndicative: { singular: { first: "scelgo", second: "scegli", third: "sceglie" }, plural: { first: "scegliamo", second: "scegliete", third:"scelgono" }}},
    { id: 223, it: "tenere", pl: "trzymać", presentIndicative: { singular: { first: "tengo", second: "tieni", third: "tiene" }, plural: { first: "teniamo", second: "tenete", third:"tengono" }}},
]

const all = [
    ...regular1A,
    ...regular1B,
    ...regular2,
    ...regular3A,
    ...regular3B,
    ...regular3AB,
    ...regularReflexive,
    ...irregular,
]

const config = {
    regular1A,
    regular1B,
    regular2,
    regular3A,
    regular3B,
    regular3AB,
    regularReflexive,
    irregular,
    all,
    test,
    newOrHard
}

export default config