import { Card } from './types'

const test: Card[] = [
    { id: 1, it: "one", pl: "jeden", presentIndicative: { singular: { first: "1-s1", second: "1-s2", third: "1-s3" }, plural: { first: "1-p1", second: "1-p2", third: "1-p3" }}},
    { id: 2, it: "two", pl: "dwa", presentIndicative: { singular: { first: "2-s1", second: "2-s2", third: "2-s3" }, plural: { first: "2-p1", second: "2-p2", third: "2-p3" }}},
    { id: 3, it: "three", pl: "trzy", presentIndicative: { singular: { first: "3-s1", second: "3-s2", third: "3-s3" }, plural: { first: "3-p1", second: "3-p2", third: "3-p3" }}},
    { id: 4, it: "four", pl: "cztery", presentIndicative: { singular: { first: "4-s1", second: "4-s2", third: "4-s3" }, plural: { first: "4-p1", second: "4-p2", third: "4-p3" }}},
    { id: 5, it: "five", pl: "pięć", presentIndicative: { singular: { first: "5-s1", second: "5-s2", third: "5-s3" }, plural: { first: "5-p1", second: "5-p2", third: "5-p3" }}},
    { id: 6, it: "six", pl: "sześć", presentIndicative: { singular: { first: "6-s1", second: "6-s2", third: "6-s3" }, plural: { first: "6-p1", second: "6-p2", third: "6-p3" }}},
]

const regular1A: Card[] = [
    { id: 1, it: "diventare", pl: "stawać się, zostawać", presentIndicative: { singular: { first: "divento", second: "diventi", third: "diventa" }, plural: { first: "diventiamo", second: "diventate", third:"diventano" }}},
    { id: 2, it: "abitare", pl: "mieszkać", presentIndicative: { singular: { first: "abito", second: "abiti", third: "abita" }, plural: { first: "abitiamo", second: "abitate", third:"abitano" }}},
    { id: 3, it: "imparare", pl: "uczyć się", presentIndicative: { singular: { first: "imparo", second: "impari", third: "impara" }, plural: { first: "impariamo", second: "imparate", third:"imparano" }}},
    { id: 4, it: "cucinare", pl: "gotować", presentIndicative: { singular: { first: "cucino", second: "cucini", third: "cucina" }, plural: { first: "cuciniamo", second: "cucinate", third:"cucinano" }}},
    { id: 5, it: "lavorare", pl: "pracować", presentIndicative: { singular: { first: "lavoro", second: "lavori", third: "lavora" }, plural: { first: "lavoriamo", second: "lavorate", third:"lavorano" }}},
    { id: 6, it: "lavare", pl: "myć, prać", presentIndicative: { singular: { first: "lavo", second: "lavi", third: "lava" }, plural: { first: "laviamo", second: "lavate", third:"lavano" }}},
    { id: 7, it: "pranzare", pl: "jeść obiad", presentIndicative: { singular: { first: "pranzo", second: "pranzi", third: "pranza" }, plural: { first: "pranziamo", second: "pranzate", third:"pranzano" }}},
    { id: 8, it: "cenare", pl: "jeść kolację", presentIndicative: { singular: { first: "ceno", second: "ceni", third: "cena" }, plural: { first: "ceniamo", second: "cenate", third:"cenano" }}},
    { id: 9, it: "ascoltare", pl: "słuchać", presentIndicative: { singular: { first: "ascolto", second: "ascolti", third: "ascolta" }, plural: { first: "ascoltiamo", second: "ascoltate", third:"ascoltano" }}},
    { id: 10, it: "guardare", pl: "oglądać", presentIndicative: { singular: { first: "guardo", second: "guardi", third: "guarda" }, plural: { first: "guardiamo", second: "guardate", third:"guardano" }}},
    { id: 11, it: "trovare", pl: "znajdować", presentIndicative: { singular: { first: "trovo", second: "trovi", third: "trova" }, plural: { first: "troviamo", second: "trovate", third:"trovano" }}},
    { id: 12, it: "nuotare", pl: "pływać", presentIndicative: { singular: { first: "nuoto", second: "nuoti", third: "nuota" }, plural: { first: "nuotiamo", second: "nuotate", third:"nuotano" }}},
    { id: 13, it: "portare", pl: "nieść", presentIndicative: { singular: { first: "porto", second: "porti", third: "porta" }, plural: { first: "portiamo", second: "portate", third:"portano" }}},
    { id: 14, it: "tornare", pl: "wracać", presentIndicative: { singular: { first: "torno", second: "torni", third: "torna" }, plural: { first: "torniamo", second: "tornate", third:"tornano" }}},
    { id: 15, it: "entrare", pl: "wchodzić", presentIndicative: { singular: { first: "entro", second: "entri", third: "entra" }, plural: { first: "entriamo", second: "entrate", third:"entrano" }}},
    { id: 16, it: "camminare", pl: "chodzić", presentIndicative: { singular: { first: "cammino", second: "cammini", third: "cammina" }, plural: { first: "camminiamo", second: "camminate", third:"camminano" }}},
    { id: 17, it: "tirare", pl: "ciągnąć", presentIndicative: { singular: { first: "tiro", second: "tiri", third: "tira" }, plural: { first: "tiriamo", second: "tirate", third:"tirano" }}},
    { id: 18, it: "ballare", pl: "tańczyć", presentIndicative: { singular: { first: "ballo", second: "balli", third: "balla" }, plural: { first: "balliamo", second: "ballate", third:"ballano" }}},
    { id: 19, it: "cantare", pl: "śpiewać", presentIndicative: { singular: { first: "canto", second: "canti", third: "canta" }, plural: { first: "cantiamo", second: "cantate", third:"cantano" }}},
    { id: 20, it: "usare", pl: "używać", presentIndicative: { singular: { first: "uso", second: "usi", third: "usa" }, plural: { first: "usiamo", second: "usate", third:"usano" }}},
    { id: 21, it: "iniziare", pl: "rozpoczynać, włączać", presentIndicative: { singular: { first: "inizio", second: "inizii", third: "inizia" }, plural: { first: "iniziiamo", second: "iniziate", third:"iniziano" }}},
    { id: 22, it: "parlare", pl: "mówić, rozmawiać", presentIndicative: { singular: { first: "parlo", second: "parli", third: "parla" }, plural: { first: "parliamo", second: "parlate", third:"parlano" }}},
    { id: 23, it: "ordinare", pl: "porządkować, rozkazywać, zamawiać", presentIndicative: { singular: { first: "ordino", second: "ordini", third: "ordina" }, plural: { first: "ordiniamo", second: "ordinate", third:"ordinano" }}},
    { id: 24, it: "pensare", pl: "myśleć", presentIndicative: { singular: { first: "penso", second: "pensi", third: "pensa" }, plural: { first: "pensiamo", second: "pensate", third:"pensano" }}},
    { id: 25, it: "telefonare", pl: "telefonować do kogoś", presentIndicative: { singular: { first: "telefono", second: "telefoni", third: "telefona" }, plural: { first: "telefoniamo", second: "telefonate", third:"telefonano" }}},
    { id: 26, it: "mandare", pl: "wysyłać", presentIndicative: { singular: { first: "mando", second: "mandi", third: "manda" }, plural: { first: "mandiamo", second: "mandate", third:"mandano" }}},
    { id: 27, it: "salutare", pl: "witać", presentIndicative: { singular: { first: "saluto", second: "saluti", third: "saluta" }, plural: { first: "salutiamo", second: "salutate", third:"salutano" }}},
    { id: 28, it: "incontrare", pl: "spotykać", presentIndicative: { singular: { first: "incontro", second: "incontri", third: "incontra" }, plural: { first: "incontriamo", second: "incontrate", third:"incontrano" }}},
    { id: 29, it: "visitare", pl: "odwiedzać", presentIndicative: { singular: { first: "visito", second: "visiti", third: "visita" }, plural: { first: "visitiamo", second: "visitate", third:"visitano" }}},
    { id: 30, it: "invitare", pl: "zapraszać", presentIndicative: { singular: { first: "invito", second: "inviti", third: "invita" }, plural: { first: "invitiamo", second: "invitate", third:"invitano" }}},
    { id: 31, it: "scusare", pl: "wybaczać", presentIndicative: { singular: { first: "scuso", second: "scusi", third: "scusa" }, plural: { first: "scusiamo", second: "scusate", third:"scusano" }}},
    { id: 32, it: "desiderare", pl: "życzyć sobie, chcieć", presentIndicative: { singular: { first: "desidero", second: "desideri", third: "desidera" }, plural: { first: "desideriamo", second: "desiderate", third:"desiderano" }}},
    { id: 33, it: "amare", pl: "kochać", presentIndicative: { singular: { first: "amo", second: "ami", third: "ama" }, plural: { first: "amiamo", second: "amate", third:"amano" }}},
    { id: 34, it: "sperare", pl: "mieć nadzieję", presentIndicative: { singular: { first: "spero", second: "speri", third: "spera" }, plural: { first: "speriamo", second: "sperate", third:"sperano" }}},
    { id: 35, it: "ricordare", pl: "pamiętać kogoś/coś", presentIndicative: { singular: { first: "ricordo", second: "ricordi", third: "ricorda" }, plural: { first: "ricordiamo", second: "ricordate", third:"ricordano" }}},
    { id: 36, it: "aiutare", pl: "pomagać komuś", presentIndicative: { singular: { first: "aiuto", second: "aiuti", third: "aiuta" }, plural: { first: "aiutiamo", second: "aiutate", third:"aiutano" }}},
    { id: 37, it: "aspettare", pl: "czekać na kogoś/coś", presentIndicative: { singular: { first: "aspetto", second: "aspetti", third: "aspetta" }, plural: { first: "aspettiamo", second: "aspettate", third:"aspettano" }}},
    { id: 38, it: "costare", pl: "kosztować", presentIndicative: { singular: { first: "costo", second: "costi", third: "costa" }, plural: { first: "costiamo", second: "costate", third:"costano" }}},
    { id: 39, it: "comprare", pl: "kupować", presentIndicative: { singular: { first: "compro", second: "compri", third: "compra" }, plural: { first: "compriamo", second: "comprate", third:"comprano" }}},
    { id: 40, it: "guadagnare", pl: "zarabiać", presentIndicative: { singular: { first: "guadagno", second: "guadagni", third: "guadagna" }, plural: { first: "guadagniamo", second: "guadagnate", third:"guadagnano" }}},
]
const regular1B: Card[] = [
    { id: 41, it: "mangiare", pl: "jeść", presentIndicative: { singular: { first: "mangio", second: "mangi", third: "mangia" }, plural: { first: "mangiamo", second: "mangiate", third:"mangiano" }}},
    { id: 42, it: "studiare", pl: "uczyć się, studiować", presentIndicative: { singular: { first: "studio", second: "studi", third: "studia" }, plural: { first: "studiamo", second: "studiate", third:"studiano" }}},
    { id: 43, it: "lasciare", pl: "zostawiać", presentIndicative: { singular: { first: "lascio", second: "lasci", third: "lascia" }, plural: { first: "lasciamo", second: "lasciate", third:"lasciano" }}},
    { id: 44, it: "cambiare", pl: "zmieniać", presentIndicative: { singular: { first: "cambio", second: "cambi", third: "cambia" }, plural: { first: "cambiamo", second: "cambiate", third:"cambiano" }}},
]
const regular2: Card[] = [
    { id: 45, it: "prendere", pl: "brać, kupować, jeść, pić", presentIndicative: { singular: { first: "prendo", second: "prendi", third: "prende" }, plural: { first: "prendiamo", second: "prendete", third:"prendono" }}},
    { id: 46, it: "mettere", pl: "kłaść, zakładać", presentIndicative: { singular: { first: "metto", second: "metti", third: "mette" }, plural: { first: "mettiamo", second: "mettete", third:"mettono" }}},
    { id: 47, it: "vedere", pl: "widzieć", presentIndicative: { singular: { first: "vedo", second: "vedi", third: "vede" }, plural: { first: "vediamo", second: "vedete", third:"vedono" }}},
    { id: 48, it: "vendere", pl: "sprzedawać", presentIndicative: { singular: { first: "vendo", second: "vendi", third: "vende" }, plural: { first: "vendiamo", second: "vendete", third:"vendono" }}},
    { id: 49, it: "chiedere", pl: "pytać, prosić", presentIndicative: { singular: { first: "chiedo", second: "chiedi", third: "chiede" }, plural: { first: "chiediamo", second: "chiedete", third:"chiedono" }}},
    { id: 50, it: "rispondere", pl: "odpowiadać", presentIndicative: { singular: { first: "rispondo", second: "rispondi", third: "risponde" }, plural: { first: "rispondiamo", second: "rispondete", third:"rispondono" }}},
    { id: 51, it: "ripetere", pl: "powtarzać", presentIndicative: { singular: { first: "ripeto", second: "ripeti", third: "ripete" }, plural: { first: "ripetiamo", second: "ripetete", third:"ripetono" }}},
    { id: 52, it: "vivere", pl: "żyć, mieszkać", presentIndicative: { singular: { first: "vivo", second: "vivi", third: "vive" }, plural: { first: "viviamo", second: "vivete", third:"vivono" }}},
    { id: 53, it: "nascere", pl: "urodzić się", presentIndicative: { singular: { first: "nasco", second: "nasci", third: "nasce" }, plural: { first: "nasciamo", second: "nascete", third:"nascono" }}},
    { id: 54, it: "crescere", pl: "rosnąć", presentIndicative: { singular: { first: "cresco", second: "cresci", third: "cresce" }, plural: { first: "cresciamo", second: "crescete", third:"crescono" }}},
    { id: 55, it: "perdere", pl: "przegrać, stracić", presentIndicative: { singular: { first: "perdo", second: "perdi", third: "perde" }, plural: { first: "perdiamo", second: "perdete", third:"perdono" }}},
    { id: 56, it: "scendere", pl: "schodzić", presentIndicative: { singular: { first: "scendo", second: "scendi", third: "scende" }, plural: { first: "scendiamo", second: "scendete", third:"scendono" }}},
    { id: 57, it: "scrivere", pl: "pisać", presentIndicative: { singular: { first: "scrivo", second: "scrivi", third: "scrive" }, plural: { first: "scriviamo", second: "scrivete", third:"scrivono" }}},
    { id: 58, it: "rompere", pl: "łamać, rozbijać", presentIndicative: { singular: { first: "rompo", second: "rompi", third: "rompe" }, plural: { first: "rompiamo", second: "rompete", third:"rompono" }}},
    { id: 59, it: "correre", pl: "biegać", presentIndicative: { singular: { first: "corro", second: "corri", third: "corre" }, plural: { first: "corriamo", second: "correte", third:"corrono" }}},
    { id: 60, it: "rendere", pl: "oddawać", presentIndicative: { singular: { first: "rendo", second: "rendi", third: "rende" }, plural: { first: "rendiamo", second: "rendete", third:"rendono" }}},
    { id: 61, it: "chiudere", pl: "zamykać", presentIndicative: { singular: { first: "chiudo", second: "chiudi", third: "chiude" }, plural: { first: "chiudiamo", second: "chiudete", third:"chiudono" }}},
    { id: 62, it: "spingere", pl: "pchać", presentIndicative: { singular: { first: "spingo", second: "spingi", third: "spinge" }, plural: { first: "spingiamo", second: "spingete", third:"spingono" }}},
    { id: 63, it: "accendere", pl: "włączać, zapalać", presentIndicative: { singular: { first: "accendo", second: "accendi", third: "accende" }, plural: { first: "accendiamo", second: "accendete", third:"accendono" }}},
    { id: 64, it: "credere", pl: "wierzyć, uważać", presentIndicative: { singular: { first: "credo", second: "credi", third: "crede" }, plural: { first: "crediamo", second: "credete", third:"credono" }}},
    { id: 65, it: "godere", pl: "cieszyć się czymś, korzystać z czegoś", presentIndicative: { singular: { first: "godo", second: "godi", third: "gode" }, plural: { first: "godiamo", second: "godete", third:"godono" }}},
    { id: 66, it: "leggere", pl: "czytać", presentIndicative: { singular: { first: "leggo", second: "leggi", third: "legge" }, plural: { first: "leggiamo", second: "leggete", third:"leggono" }}},
    { id: 67, it: "vincere", pl: "zwyciężać", presentIndicative: { singular: { first: "vinco", second: "vinci", third: "vince" }, plural: { first: "vinciamo", second: "vincete", third:"vincono" }}},
    { id: 68, it: "conoscere", pl: "znać", presentIndicative: { singular: { first: "conosco", second: "conosci", third: "conosce" }, plural: { first: "conosciamo", second: "conoscete", third:"conoscono" }}},
]
const regular3A: Card[] = [
    { id: 69, it: "sentire", pl: "słyszeć, czuć", presentIndicative: { singular: { first: "sento", second: "senti", third: "sente" }, plural: { first: "sentiamo", second: "sentite", third:"sentono" }}},
    { id: 70, it: "dormire", pl: "spać", presentIndicative: { singular: { first: "dormo", second: "dormi", third: "dorme" }, plural: { first: "dormiamo", second: "dormite", third:"dormono" }}},
    { id: 71, it: "partire", pl: "wyjeżdżać", presentIndicative: { singular: { first: "parto", second: "parti", third: "parte" }, plural: { first: "partiamo", second: "partite", third:"partono" }}},
    { id: 72, it: "coprire", pl: "przykrywać", presentIndicative: { singular: { first: "copro", second: "copri", third: "copre" }, plural: { first: "copriamo", second: "coprite", third:"coprono" }}},
    { id: 73, it: "scoprire", pl: "odkrywać", presentIndicative: { singular: { first: "scopro", second: "scopri", third: "scopre" }, plural: { first: "scopriamo", second: "scoprite", third:"scoprono" }}},
    { id: 74, it: "aprire", pl: "otwierać", presentIndicative: { singular: { first: "apro", second: "apri", third: "apre" }, plural: { first: "apriamo", second: "aprite", third:"aprono" }}},
    { id: 75, it: "offrire", pl: "ofiarować, oferować", presentIndicative: { singular: { first: "offro", second: "offri", third: "offre" }, plural: { first: "offriamo", second: "offrite", third:"offrono" }}},
    { id: 76, it: "soffrire", pl: "cierpieć", presentIndicative: { singular: { first: "soffro", second: "soffri", third: "soffre" }, plural: { first: "soffriamo", second: "soffrite", third:"soffrono" }}},
    { id: 77, it: "servire", pl: "służyć", presentIndicative: { singular: { first: "servo", second: "servi", third: "serve" }, plural: { first: "serviamo", second: "servite", third:"servono" }}},
    { id: 78, it: "pulire", pl: "czyścić", presentIndicative: { singular: { first: "pulo", second: "puli", third: "pule" }, plural: { first: "puliamo", second: "pulite", third:"pulono" }}},
    { id: 79, it: "finire", pl: "kończyć", presentIndicative: { singular: { first: "finisco", second: "finisci", third: "finisce" }, plural: { first: "finiamo", second: "finite", third:"finiscono" }}},
]
const regular3B: Card[] = [
    { id: 80, it: "capire", pl: "rozumieć", presentIndicative: { singular: { first: "capisco", second: "capisci", third: "capisce" }, plural: { first: "capiamo", second: "capite", third:"capiscono" }}},
    { id: 81, it: "dimagrire", pl: "chudnąć", presentIndicative: { singular: { first: "dimagrisco", second: "dimagrisci", third: "dimagrisce" }, plural: { first: "dimagriamo", second: "dimagrite", third:"dimagriscono" }}},
    { id: 82, it: "pulire", pl: "czyścić", presentIndicative: { singular: { first: "pulisco", second: "pulisci", third: "pulisce" }, plural: { first: "puliamo", second: "pulite", third:"puliscono" }}},
    { id: 83, it: "unire", pl: "jednoczyć, łączyć", presentIndicative: { singular: { first: "unisco", second: "unisci", third: "unisce" }, plural: { first: "uniamo", second: "unite", third:"uniscono" }}},
    { id: 84, it: "preferire", pl: "woleć", presentIndicative: { singular: { first: "preferisco", second: "preferisci", third: "preferisce" }, plural: { first: "preferiamo", second: "preferite", third:"preferiscono" }}},
    { id: 85, it: "costruire", pl: "budować", presentIndicative: { singular: { first: "costruisco", second: "costruisci", third: "costruisce" }, plural: { first: "costruiamo", second: "costruite", third:"costruiscono" }}},
]
const regular3AB: Card[] = [
    { id: 86, it: "tossire", pl: "kaszleć", presentIndicative: { singular: { first: "tosso / tossisco", second: "tossi / tossisci", third: "tosse / tossisce" }, plural: { first: "tossiamo / tossiamo", second: "tossite / tossite", third:"tossono / tossiscono" }}},
    { id: 87, it: "mentire", pl: "kłamać", presentIndicative: { singular: { first: "mento / mentisco", second: "menti / mentisci", third: "mente / mentisce" }, plural: { first: "mentiamo / mentiamo", second: "mentite / mentite", third:"mentono / mentiscono" }}},
]
const regularReflexive: Card[] = [
    { id: 88, it: "chiamarsi", pl: "nazywać się", presentIndicative: { singular: { first: "mi chiamo", second: "ti chiami", third: "si chiama" }, plural: { first: "ci chiamiamo", second: "vi chiamate", third:"si chiamano" }}},
    { id: 89, it: "comportarsi", pl: "zachowywać się", presentIndicative: { singular: { first: "mi comporto", second: "ti comporti", third: "si comporta" }, plural: { first: "ci comportiamo", second: "vi comportate", third:"si comportano" }}},
    { id: 90, it: "scusarsi", pl: "przeprosić", presentIndicative: { singular: { first: "mi scuso", second: "ti scusi", third: "si scusa" }, plural: { first: "ci scusiamo", second: "vi scusate", third:"si scusano" }}},
    { id: 91, it: "abituarsi", pl: "przyzwyczaić się", presentIndicative: { singular: { first: "mi abituo", second: "ti abitui", third: "si abitua" }, plural: { first: "ci abituiamo", second: "vi abituate", third:"si abituano" }}},
    { id: 92, it: "alzarsi", pl: "wstawać", presentIndicative: { singular: { first: "mi alzo", second: "ti alzi", third: "si alza" }, plural: { first: "ci alziamo", second: "vi alzate", third:"si alzano" }}},
    { id: 93, it: "lavarsi", pl: "myć się", presentIndicative: { singular: { first: "mi lavo", second: "ti lavi", third: "si lava" }, plural: { first: "ci laviamo", second: "vi lavate", third:"si lavano" }}},
    { id: 94, it: "incontrarsi", pl: "spotykać się", presentIndicative: { singular: { first: "mi incontro", second: "ti incontri", third: "si incontra" }, plural: { first: "ci incontriamo", second: "vi incontrate", third:"si incontrano" }}},
    { id: 95, it: "ritrovarsi", pl: "odnaleźć się", presentIndicative: { singular: { first: "mi ritrovo", second: "ti ritrovi", third: "si ritrova" }, plural: { first: "ci ritroviamo", second: "vi ritrovate", third:"si ritrovano" }}},
    { id: 96, it: "svegliarsi", pl: "budzić się", presentIndicative: { singular: { first: "mi sveglio", second: "ti sveglii", third: "si sveglia" }, plural: { first: "ci svegliiamo", second: "vi svegliate", third:"si svegliano" }}},
    { id: 97, it: "concentrarsi", pl: "koncentrować się", presentIndicative: { singular: { first: "mi concentro", second: "ti concentri", third: "si concentra" }, plural: { first: "ci concentriamo", second: "vi concentrate", third:"si concentrano" }}},
    { id: 98, it: "comportarsi", pl: "zachowywać się", presentIndicative: { singular: { first: "mi comporto", second: "ti comporti", third: "si comporta" }, plural: { first: "ci comportiamo", second: "vi comportate", third:"si comportano" }}},
    { id: 99, it: "addormentarsi", pl: "zasnąć", presentIndicative: { singular: { first: "mi addormento", second: "ti addormenti", third: "si addormenta" }, plural: { first: "ci addormentiamo", second: "vi addormentate", third:"si addormentano" }}},
    { id: 100, it: "ammalarsi", pl: "zachorować", presentIndicative: { singular: { first: "mi ammalo", second: "ti ammali", third: "si ammala" }, plural: { first: "ci ammaliamo", second: "vi ammalate", third:"si ammalano" }}},
    { id: 101, it: "esprimersi", pl: "wyrażać się", presentIndicative: { singular: { first: "mi esprimo", second: "ti esprimi", third: "si esprime" }, plural: { first: "ci esprimiamo", second: "vi esprimete", third:"si esprimono" }}},
    { id: 102, it: "vedersi", pl: "widzieć się", presentIndicative: { singular: { first: "mi vedo", second: "ti vedi", third: "si vede" }, plural: { first: "ci vediamo", second: "vi vedete", third:"si vedono" }}},
    { id: 103, it: "perdersi", pl: "gubić się", presentIndicative: { singular: { first: "mi perdo", second: "ti perdi", third: "si perde" }, plural: { first: "ci perdiamo", second: "vi perdete", third:"si perdono" }}},
    { id: 104, it: "conoscersi", pl: "znać się", presentIndicative: { singular: { first: "mi conosco", second: "ti conosci", third: "si conosce" }, plural: { first: "ci conosciamo", second: "vi conoscete", third:"si conoscono" }}},
    { id: 105, it: "vestirsi", pl: "ubierać się", presentIndicative: { singular: { first: "mi vesto", second: "ti vesti", third: "si veste" }, plural: { first: "ci vestiamo", second: "vi vestite", third:"si vestono" }}},
    { id: 106, it: "divertirsi", pl: "bawić się", presentIndicative: { singular: { first: "mi diverto", second: "ti diverti", third: "si diverte" }, plural: { first: "ci divertiamo", second: "vi divertite", third:"si divertono" }}},
    { id: 107, it: "congratularsi con qcn.", pl: "gratulować komuś", presentIndicative: { singular: { first: "mi congratulo con qcn.", second: "ti congratuli con qcn.", third: "si congratula con qcn." }, plural: { first: "ci congratuliamo con qcn.", second: "vi congratulate con qcn.", third:"si congratulano con qcn." }}},
    { id: 108, it: "fidarsi di qcn.", pl: "ufać komuś", presentIndicative: { singular: { first: "mi fido di qcn.", second: "ti fidi di qcn.", third: "si fida di qcn." }, plural: { first: "ci fidiamo di qcn.", second: "vi fidate di qcn.", third:"si fidano di qcn." }}},
    { id: 109, it: "pentirsi di qcs.", pl: "żałować czegoś", presentIndicative: { singular: { first: "mi pento di qcs.", second: "ti penti di qcs.", third: "si pente di qcs." }, plural: { first: "ci pentiamo di qcs.", second: "vi pentite di qcs.", third:"si pentono di qcs." }}},
]
const irregular: Card[] = [    { id: 110, it: "essere", pl: "(być)", presentIndicative: { singular: { first: "sono", second: "sei", third: "è" }, plural: { first: "siamo", second: "siete", third:"sono" }}},
    { id: 111, it: "avere", pl: "(mieć)", presentIndicative: { singular: { first: "ho", second: "hai", third: "ha" }, plural: { first: "abbiamo", second: "avete", third:"hanno" }}},
    { id: 112, it: "volere", pl: "(chcieć)", presentIndicative: { singular: { first: "voglio", second: "vuoi", third: "vuole" }, plural: { first: "vogliamo", second: "volete", third:"vogliono" }}},
    { id: 113, it: "potere", pl: "(móc)", presentIndicative: { singular: { first: "posso", second: "puoi", third: "può" }, plural: { first: "possiamo", second: "potete", third:"possono" }}},
    { id: 114, it: "dovere", pl: "(musieć)", presentIndicative: { singular: { first: "devo", second: "devi", third: "deve" }, plural: { first: "dobbiamo", second: "dovete", third:"devono" }}},
    { id: 115, it: "sapere", pl: "(umieć, znać, wiedzieć)", presentIndicative: { singular: { first: "so", second: "sai", third: "sa" }, plural: { first: "sappiamo", second: "sapete", third:"sanno" }}},
    { id: 116, it: "stare", pl: "(czuć się)", presentIndicative: { singular: { first: "sto", second: "stai", third: "sta" }, plural: { first: "stiamo", second: "state", third:"stanno" }}},
    { id: 117, it: "fare", pl: "(robić)", presentIndicative: { singular: { first: "faccio", second: "fai", third: "fa" }, plural: { first: "facciamo", second: "fate", third:"fanno" }}},
    { id: 118, it: "andare", pl: "(iść, jechać)", presentIndicative: { singular: { first: "vado", second: "vai", third: "va" }, plural: { first: "andiamo", second: "andate", third:"vanno" }}},
    { id: 119, it: "uscire", pl: "(wychodzić)", presentIndicative: { singular: { first: "esco", second: "esci", third: "esce" }, plural: { first: "usciamo", second: "uscite", third:"escono" }}},
    { id: 120, it: "bere", pl: "(pić)", presentIndicative: { singular: { first: "bevo", second: "bevi", third: "beve" }, plural: { first: "beviamo", second: "bevete", third:"bevono" }}},
    { id: 121, it: "dare", pl: "(dawać)", presentIndicative: { singular: { first: "do", second: "dai", third: "dà" }, plural: { first: "diamo", second: "date", third:"danno" }}},
    { id: 122, it: "dire", pl: "(mówić)", presentIndicative: { singular: { first: "dico", second: "dici", third: "dice" }, plural: { first: "diciamo", second: "dite", third:"dicono" }}},
    { id: 123, it: "tradurre", pl: "(tłumaczyć)", presentIndicative: { singular: { first: "traduco", second: "traduci", third: "traduce" }, plural: { first: "traduciamo", second: "traducete", third:"traducono" }}},
    { id: 124, it: "morire", pl: "(umierać)", presentIndicative: { singular: { first: "muoio", second: "muori", third: "muore" }, plural: { first: "moriamo", second: "morite", third:"muoiono" }}},
    { id: 125, it: "cuocere", pl: "(gotować)", presentIndicative: { singular: { first: "cuocio", second: "cuoci", third: "cuoce" }, plural: { first: "cuociamo", second: "cuocete", third:"cuociono" }}},
    { id: 126, it: "sciare", pl: "(jeździć na nartach)", presentIndicative: { singular: { first: "scio", second: "scii", third: "scia" }, plural: { first: "sciamo", second: "sciate", third:"sciano" }}},
    { id: 127, it: "giocare", pl: "(grać [w grę])", presentIndicative: { singular: { first: "gioco", second: "giochi", third: "gioca" }, plural: { first: "giochiamo", second: "giocate", third:"giocano" }}},
    { id: 128, it: "cercare", pl: "(szukać)", presentIndicative: { singular: { first: "cerco", second: "cerchi", third: "cerca" }, plural: { first: "cerchiamo", second: "cercate", third:"cercano" }}},
    { id: 129, it: "toccare", pl: "(dotykać)", presentIndicative: { singular: { first: "tocco", second: "tocchi", third: "tocca" }, plural: { first: "tocchiamo", second: "toccate", third:"toccano" }}},
    { id: 130, it: "spiegare", pl: "(wyjaśniać)", presentIndicative: { singular: { first: "spiego", second: "spieghi", third: "spiega" }, plural: { first: "spieghiamo", second: "spiegate", third:"spiegano" }}},
    { id: 131, it: "pagare", pl: "(płacić)", presentIndicative: { singular: { first: "pago", second: "paghi", third: "paga" }, plural: { first: "paghiamo", second: "pagate", third:"pagano" }}},
    { id: 132, it: "venire", pl: "(przychodzić)", presentIndicative: { singular: { first: "vengo", second: "vieni", third: "viene" }, plural: { first: "veniamo", second: "venite", third:"vengono" }}},
    { id: 133, it: "salire", pl: "(wychodzić, iść w górę)", presentIndicative: { singular: { first: "salgo", second: "sali", third: "sale" }, plural: { first: "saliamo", second: "salite", third:"salgono" }}},
    { id: 134, it: "rimanere", pl: "(zostawać)", presentIndicative: { singular: { first: "rimango", second: "rimani", third: "rimane" }, plural: { first: "rimaniamo", second: "rimanete", third:"rimangono" }}},
    { id: 135, it: "sedersi", pl: "(siadać)", presentIndicative: { singular: { first: "mi siedo; mi seggo", second: "ti siedi", third: "si siede" }, plural: { first: "ci sediamo", second: "vi sedete", third:"si siedono; si seggono" }}},
    { id: 136, it: "innervosire", pl: "(denerwować się)", presentIndicative: { singular: { first: "mi innervosisco", second: "ti innervosisci", third: "si innervosisce" }, plural: { first: "ci innervosiamo", second: "vi innervosite", third:"si nnervosiscono" }}},
    { id: 137, it: "piacere", pl: "(podobać się)", presentIndicative: { singular: { first: "mi piace", second: "ti piace", third: "gli piace" }, plural: { first: "ci piace", second: "vi piace", third:"gli piace" }}},
    { id: 138, it: "dispiacere", pl: "(być przykro)", presentIndicative: { singular: { first: "mi dispiace", second: "ti dispiace", third: "gli dispiace" }, plural: { first: "ci dispiace", second: "vi dispiace", third:"gli dispiace" }}},
    { id: 139, it: "mancare", pl: "(brakować)", presentIndicative: { singular: { first: "mi manca", second: "ti manca", third: "gli manca" }, plural: { first: "ci manca", second: "vi manca", third:"gli manca" }}},
    { id: 140, it: "interessare", pl: "(dotoczyć, interesować)", presentIndicative: { singular: { first: "mi interessa", second: "ti interessa", third: "gli interessa" }, plural: { first: "ci interessa", second: "vi interessa", third:"gli interessa" }}},
]

const all = [
    ...regular1A,
    ...regular1B,
    ...regular2,
    ...regular3A,
    ...regular3B,
    ...regular3AB,
    ...regularReflexive,
    ...irregular,
]

const config = {
    regular1A,
    regular1B,
    regular2,
    regular3A,
    regular3B,
    regular3AB,
    regularReflexive,
    irregular,
    all,
    // all: test
}

export default config